### ISSUE TITLE
Use Jlink to reduce container image size

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#10]
**Problem**
A short explanation of the problem, including relevant restrictions.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
- System Integrator

**Exit Criteria**
Reduce container image size ( < 300MB )

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1-4

**Additional context (optional)**
- https://docs.oracle.com/en/java/javase/11/tools/jlink.html

**Comment by pierDipi** [comment]
The branch contains a partial work on this issue: https://github.com/knative-sandbox/eventing-kafka-broker/compare/master...pierDipi:modular-world

/unassign
/cc @slinkydeveloper

**Comment by InfoSec812** [comment]
Just curious, but why not use GraalVM native-image? I would think it would produce an even smaller image, faster start-up, and lower memory overhead.

**Comment by slinkydeveloper** [comment]
@InfoSec812 AFAIK on long run the graalvm ce GC performs definitely worse than the jdk one. We don't really need a fast start-up, we mostly care about image size and performance on the long run (the broker data-plane image may technically remain up for the lifetime of the cluster)
