### ISSUE TITLE
Drop verbose logging in GitHub Actions

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#1067]
**Problem**

Going through logs to find a failed test in GH actions is painful since there are all logs even of succeeded tests, I think we shouldn't use the `-v` flag in there.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Contributor and Maintainer

**Exit Criteria**
Failed tests are easy to discover.

**Additional context (optional)**
- See any recent periodic failed action 

/good-first-issue

**Comment by slinkydeveloper** [comment]
I honestly like the verbose flag :smile: It allows me to see if all tests were executed

**Comment by pierDipi** [comment]
we can enable it on PRs and remove it for scheduled jobs, wdyt?

**Comment by slinkydeveloper** [comment]
What if scheduled jobs fail? without verbose logs, it's going to be harder to debug them :)

**Comment by pierDipi** [comment]
When a test fails go prints logs https://golang.org/pkg/testing/#T.Log

**Comment by slinkydeveloper** [comment]
then let's disable it for scheduled jobs
