### ISSUE TITLE
Tracing with Zipkin doesn't appear to work

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-kafka-broker#1098]
**Describe the bug**
Tracing support doesn't appear to be working

 **Expected behavior**
I've configured my broker with the sample configs from eventing to have a [Zipkin service](https://github.com/knative/eventing/blob/main/test/config/monitoring/monitoring.yaml) running in knative-eventing and a [config-tracing](https://github.com/knative/eventing/blob/main/test/config/configmaps/tracing.yaml) that forwards with a sample-rate of 1.0.

I configured the dispatcher to log at DEBUG level and see these lines in the logs:

```
{"@timestamp":"2021-07-15T15:37:07.873Z","@version":"1","message":"Registering tracing configurations backend=ZIPKIN sampleRate=1.0 loggingDebugEnabled=true","logger_name":"dev.knative.eventing.kafka.broker.core.tracing.TracingConfig","thread_name":"main","level":"INFO","level_value":20000,"backend":"ZIPKIN","sampleRate":1.0,"loggingDebugEnabled":true}
{"@timestamp":"2021-07-15T15:37:07.972Z","@version":"1","message":"Add Zipkin simple processor","logger_name":"dev.knative.eventing.kafka.broker.core.tracing.TracingConfig","thread_name":"main","level":"DEBUG","level_value":10000}
```

So it looks like it's picking up the config, but I don't see any traces being emitted in my Zipkin instance. I have a simple heartbeat source emitting to an event-display service, nothing fancy.

I tried using [ksniff](https://github.com/eldadru/ksniff) to inspect packets coming out of the dispatcher and confirmed there's nothing going out to the zipkin server.

 **To Reproduce**
Configure tracing, see if it works at all?

 **Knative release version**
0.24

**Additional context**
https://github.com/knative/eventing/issues/5589 reports that it's not working with Jaeger as well

**Comment by pierDipi** [comment]
I see them:

![image](https://user-images.githubusercontent.com/33736985/126050264-990c758a-5aad-4fe5-b102-a340b779e936.png)

Just a couple of notes:
- We don't generate the trace context if not present but we propagate it, so you need to make sure that the source is capable of sending trace metadata
- We support only w3c, b3 in WIP https://github.com/knative-sandbox/eventing-kafka-broker/issues/725
- config-tracing is this CM https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/test/config/100-config-tracing.yaml

**Comment by benmoss** [comment]
Ah, I think I was under the impression that it would be generated if not present. Thanks for the follow-up!
