### ISSUE TITLE
Summarize initial design document in INTERNALS.md

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#13]
**Problem**
The [initial design document](https://docs.google.com/document/d/10-qylWrj7Tj81EqoIiZ2AANAZNmkKe7XKmFobgZULKY/edit) can be viewed only by `knative-dev` members. We would like to have a summary in the repository in INTERNALS.md

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
- Contributor

**Exit Criteria**
A summary of the initial design document.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1-2

**Additional context (optional)**
- https://github.com/knative-sandbox/eventing-kafka-broker/pull/11#discussion_r445524859

**Comment by slinkydeveloper** [comment]
Is this still valid?

**Comment by pierDipi** [comment]
Yeah, let's close this.
