### ISSUE TITLE
Conflicting paths for ingress if objects have the same name and namespace

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka-broker#1344]
**Describe the bug**
If I create a "foo" Broker and a "foo" Channel in the same "bar" namespace, ingress path to listen will be written as `bar/foo` for both by the control plane into the contract.

 **Expected behavior**
Have some kind of separation. One of these:
- Prepend resource type: `channel/bar/foo` and `broker/bar/foo`
- Have the UID in the path: `bar/foo-123456-12356-123456`

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by pierDipi** [comment]
Do you plan to use the same Deployments (`kafka-broker-{receiver, dispatcher}`) for KafkaChannels?
Can we use a different Deployment for KafkaChannels?

**Comment by pierDipi** [comment]
We can use a different `Service` (same Deployment labels) to distinguish between the two via `host`.

**Comment by aliok** [comment]
Well, at the moment, there are separate deployments. We don't have to fix this right now - if we want to fix it.
