### ISSUE TITLE
Rename the data-plane contract entities to more general terms

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#142]
**Problem**
Now the data-plane contract (the `ConfigMap` that configures the data-plane dispatcher and receiver) uses names for entities which are strictly related to knative eventing broker terminology (broker, triggers, etc). This is confusing because these building blocks are pretty much abstracted from the knative component they implement, in particular in relation to the work is happening here https://github.com/knative-sandbox/eventing-kafka-broker/pull/134 and the eventual next plans to implement with this data-plane the KafkaSource component too.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Knative Developer

**Exit Criteria**
Better names to replace Broker/Trigger in the config map data plane contract.

**Additional context (optional)**
As raised by @pierDipi, this change may break and bring outages while upgrading to the next version of this project https://github.com/knative-sandbox/eventing-kafka-broker/pull/134#issuecomment-685672973. We need to develop a migration tool that gracefully performs the update https://github.com/knative-sandbox/eventing-kafka-broker/pull/134#issuecomment-685728594.

**Comment by pierDipi** [comment]
Another idea:

- apply the controller that stops reconciling Brokers and Triggers with the old format, it basically does nothing.

```golang
func (r *Reconciler) ReconcileKind(ctx, broker/trigger) reconciler.Event {
   return nil
}
```

- Migration tool (1)
   - migrates the old CM to a new CM using the new format

- apply the new controller that reconciles Brokers and Trigger with the new format using the new CM

- apply the data plane mounting the new CM (this step will change the k8s Service from the old receiver to the new one and we need to change names to our Deployments from `kafka-broker-receiver` to `kafka-br-receiver` and from `kafka-broker-dispatcher` to `kafka-broker-dispatcher`)

WDYT?

**Comment by slinkydeveloper** [comment]
TBH this migration process sounds hard to implement, test and in the end it won't work in all cases, it might have too much corner cases... My guess is that we should seek for a simpler one, like:

1. Remove the CM
2. Install the new components (kubectl apply)
3. Create the CM again, but empty. This will trigger the resync that rebuilds the CM with the new format
