### ISSUE TITLE
Sink: Unable to reconcile Kafka topic when SSL auth is selected

### ISSUE THREAD

**Issue by antoineco** [knative-sandbox/eventing-kafka-broker#1448]
**Describe the bug**

The part of the reconciler code below is returning `topic is not present: failed to create cluster admin: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)` when SSL authentication is selected.

https://github.com/knative-sandbox/eventing-kafka-broker/blob/42b85989cd2878c0e32b4777d0e8d163f89cca26/control-plane/pkg/reconciler/sink/kafka_sink.go#L118-L123

However, I verified using `kcat` that:
- Kafka is reachable from Kubernetes
- The provided certificates are valid and I am able to authenticate using them

 **Expected behavior**

The reconciler is able to authenticate against Kafka using SSL authentication, and to reconcile the Kafka topic.

 **To Reproduce**

```console
$ kubectl describe kafkasink mytopic
        
Name:         mytopic
Namespace:    antoineco
Labels:       <none>
Annotations:  eventing.knative.dev/creator: kubernetes-admin
              eventing.knative.dev/lastModifier: kubernetes-admin
API Version:  eventing.knative.dev/v1alpha1
Kind:         KafkaSink
Metadata:
  Creation Timestamp:  2021-11-04T16:52:33Z
  Finalizers:
    kafkasinks.eventing.knative.dev
  Generation:  1
  Resource Version:  54916330
  Self Link:         /apis/eventing.knative.dev/v1alpha1/namespaces/antoineco/kafkasinks/mytopic
  UID:               4cc8127b-5220-40cd-9059-396993385777
Spec:
  Auth:
    Secret:
      Ref:
        Name:  kafka-ssl
  Bootstrap Servers:
    ${KAFKA_HOST}:9092
  Content Mode:  structured
  Topic:         test-topic
Status:
  Address:
  Annotations:
    eventing.knative.dev/topic.owner:  external
  Conditions:
    Last Transition Time:  2021-11-04T16:52:34Z
    Status:                Unknown
    Type:                  Addressable
    Last Transition Time:  2021-11-04T16:52:34Z
    Status:                Unknown
    Type:                  ConfigMapUpdated
    Last Transition Time:  2021-11-04T16:52:34Z
    Status:                Unknown
    Type:                  ConfigParsed
    Last Transition Time:  2021-11-04T16:52:34Z
    Status:                True
    Type:                  DataPlaneAvailable
    Last Transition Time:  2021-11-04T16:52:34Z
    Message:               failed to create cluster admin: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
    Reason:                Topic is not present
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-11-04T16:52:34Z
    Message:               failed to create cluster admin: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
    Reason:                Topic is not present
    Status:                False
    Type:                  TopicReady
  Observed Generation:     1
Events:
  Type     Reason         Age                     From                  Message
  ----     ------         ----                    ----                  -------
  Warning  InternalError  9m50s (x41 over 6h38m)  kafkasink-controller  topic is not present: failed to create cluster admin: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

Use `kcat` to verify the connection:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kafka-debug
spec:
  containers:
  - name: kcat
    image: edenhill/kcat:1.7.0
    command: ['sh']
    args: ['-il']
    stdin: true
    stdinOnce: true
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kafka
      name: kafka-secret
      readOnly: true
  volumes:
  - name: kafka-secret
    secret:
      secretName: kafka-ssl
```

```console
$ kubectl attach -ti kafka-debug
kafka-debug:/#
```

```console
kafka-debug:/# kcat -L -b ${KAFKA_HOST}:9092 -X security.protocol=ssl -X ssl.ca.location=/var/run/secrets/kafka/ca.crt -X ssl.key.location=/var/run/secrets/kafka/user.key -X ssl.certificate.location=/var/run/secrets/kafka/user.crt

Metadata for all topics (from broker -1: ssl://${KAFKA_HOST}:9092/bootstrap):
 2 brokers:
  broker 0 at ${KAFKA_HOST}:9090
  broker 1 at ${KAFKA_HOST}:9091 (controller)
 9 topics:
  topic "test-topic" with 3 partitions:
    partition 0, leader 1, replicas: 1,0, isrs: 1,0
    partition 1, leader 0, replicas: 0,1, isrs: 1,0
    partition 2, leader 1, replicas: 1,0, isrs: 1,0
```

 **Knative release version**

v0.26.0

 **Additional context**

**Comment by pierDipi** [comment]
@antoineco is your secret formed like this (just to be sure)?

https://github.com/knative-sandbox/eventing-kafka-broker/blob/d452d14e48b4076eea0c45af616703527a54525d/test/pkg/testing/auth.go#L43-L48

We test SSL, so there must be something wrong with the configuration or secret.

**Comment by pierDipi** [comment]
The other thing to know is the Kafka version

**Comment by antoineco** [comment]
2.8.1

**Comment by antoineco** [comment]
@pierDipi I got back to this issue and found the source of the error.

After setting a breakpoint at `vendor/github.com/Shopify/sarama/broker.go:283` (the call to `github.com/Shopify/sarama.(*Broker).GetMetadata()`) I observe the following error:

```go
error(crypto/x509.HostnameError) {
        Certificate: *crypto/x509.Certificate {
                ...
        }
```

And the human friendly stringified version:

```
x509: cannot validate certificate for ${KAFKA_HOST} because it doesn't contain any IP SANs
```

So, the error is on the broker side for not presenting a certificate with the expected SAN.
However, I would have never found that out without running a debugger, which should be the last resort in such situation.

Let me check whether we can better capture those errors, maybe by wrapping them and bubbling them up to the caller, and send a PR in case Sarama doesn't "swallow" them (which would be a bummer).

**Comment by antoineco** [comment]
As I feared, Sarama doesn't accumulate this error for later use. It simply passes it to its logger, then de-registers the broker before moving on to the next one ([code](https://github.com/Shopify/sarama/blob/v1.28.0/client.go#L926-L930)).

After a few retries, a generic `ErrOutOfBrokers` is returned, as seen in the reconciler's logs / Kubernetes API events.

To make things worse, the default logger implementation is a no-op (discard):

```go
*log.Logger {
        mu: sync.Mutex {state: 0, sema: 0},
        prefix: "[Sarama] ",
        flag: 3,
        out: io.Writer(io.discard) {},             // <-------- no-op logger
        buf: []uint8 len: 86, cap: 144, [...],}
```

The best I can do is create an adapter between Knative's zap logger and Sarama's global `*Logger`, so that lower-level errors are at least propagated somewhere.

**Comment by pierDipi** [comment]
If anyone comes here looking for a better error message to debug this problem, unfortunately, we don't have one at the moment, see https://github.com/knative-sandbox/eventing-kafka-broker/pull/1490.
