### ISSUE TITLE
Implement KafkaSink finalizer

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#158]
**Problem**
We haven't implemented the finalizer in this PR: https://github.com/knative-sandbox/eventing-kafka-broker/pull/134

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
`*`

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
`finalizer + unit tests`

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

- The underlying topic might be managed by an external entity (eg it might be created before the CO is created), we need to make sure that we don't delete the topic if it isn't managed by us. To do that we can use the annotation `eventing.knative.dev/topic.owner` in the _**status**_ of the KafkaSink. Possible values of this annotation might be:

  - `kafkasink-controller` if it's managed by us
  - `external` if it's not

cc @matzew @slinkydeveloper if you would like to share your opinion on the additional context design/discussion.

**Comment by slinkydeveloper** [comment]
@pierDipi I think this approach is fine, go for it
