### ISSUE TITLE
Deleting the Broker ConfigMap prevents the Broker from being finalized

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#1580]
**Describe the bug**

Deleting the Broker ConfigMap prevents the Broker from being finalized since we can't get
Kafka cluster URL and credentials to remove topics.

 **Expected behavior**

A Broker can be deleted even if the ConfigMap is deleted first.

 **To Reproduce**

- Create a Broker `b`
- Remove the ConfigMap associated with `broker.spec.config`
- Remove the Broker `b`

 **Knative release version**

`<= devel`

 **Additional context**

/area broker
/area control-plane
/kind bug
/priority important-soon

**Comment by pierDipi** [comment]
cc @aliok

**Comment by aliok** [comment]
Good catch

**Comment by pierDipi** [comment]
The plan is to add a finalizer to the ConfigMap associated with the broker.

Finalizer name: ```<broker_name>.<broker_namespace>.kafka.broker.eventing.knative.dev```

After deleting the topic we can remove the finalizer.
