### ISSUE TITLE
Test FinalizeKind in the new KafkaChannel

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#1736]
**Describe the bug**

KafkaChannel has no tests for FinalizeKind.

 **Expected behavior**

Test FinalizeKind in the new KafkaChannel

 **Knative release version**

```devel```

 **Additional context**

/area control-plane
/area channel
/priority important-soon

**Comment by pierDipi** [comment]
cc @aliok

**Comment by pierDipi** [comment]
Related https://github.com/knative-sandbox/eventing-kafka-broker/issues/1798

**Comment by pierDipi** [comment]
/remove-lifecycle stale
/triage accepted

@aliok is this done?

**Comment by aliok** [comment]
/close

It is done.
