### ISSUE TITLE
Kafka Broker should send Prefer: reply HTTP header

### ISSUE THREAD

**Issue by jhill072** [knative-sandbox/eventing-kafka-broker#1770]
**Describe the bug**
According to [this spec](https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#derived-reply-events), brokers that will handle reply events need to pass along this header to indicate they can process the reply events.

This does not appear to be the case, at least with broker version 1.1 (image from gcr.io/knative-releases/knative-kafka-broker-dispatcher:devel as of this writing).

 **Expected behavior**
The HTTP header `Prefer: reply` is sent with event payload when response events will be re-routed according to [the Knative Eventing spec](https://github.com/knative/specs/blob/main/specs/eventing/data-plane.md#derived-reply-events).

 **To Reproduce**
Set up a Kafka Broker and a Trigger, then publish an event that satisfies the Trigger's filters. The request that is made is missing the "Prefer" header entirely.
I found it easy to see through https://webhook.site, since it displays all headers without having to write any consuming code.

 **Knative release version**
Eventing 1.1

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by pierDipi** [comment]
Fixed by https://github.com/knative-sandbox/eventing-kafka-broker/pull/1771

/close
