### ISSUE TITLE
Get rid of 2 skipped tests because of spec non-compliance

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka-broker#1779]
**Problem**
There are 2 tests copy&pasted from upstream knative/eventing :
- https://github.com/knative/eventing/blob/68d441013ca8c65c5b9a7f97d8f8be7e922d8a13/test/rekt/channel_test.go#L163
- https://github.com/knative/eventing/blob/68d441013ca8c65c5b9a7f97d8f8be7e922d8a13/test/rekt/channel_test.go#L211

These tests are actually testing something that's not compliant to the spec. 

This ticket is created to get rid of that non-compliance: https://github.com/knative/eventing/issues/5756

The tests could've been deleted already in this repo, but kept for awareness.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Tests removed when the non-compliance is fixed with https://github.com/knative/eventing/issues/5756

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
@aliok is this still an issue?

/remove-lifecycle stale

**Comment by aliok** [comment]
I don't have the time to check it right now, but thanks for bumping it

**Comment by pierDipi** [comment]
The tests have been removed in eventing core, we should remove those tests ASAP since the feature is beta now.
