### ISSUE TITLE
Broker status doesn't show missing sink service

### ISSUE THREAD

**Issue by mvinkler** [knative-sandbox/eventing-kafka-broker#1810]
**Problem**
When creating KafkaBroker which has non-existing service set as sink, it is not possible to tell from broker status what the issue is.

Steps to reproduce the issue:
1. Apply this yaml (dlq-service does not exist): https://knative.dev/docs/eventing/broker/kafka-broker/#create-a-kafka-broker
2. Check the broker status via `kn broker list`
3. Check `oc get events`

```
$ oc apply -f broker_dlq.yaml
broker.eventing.knative.dev/default created
$ kn broker list
NAME      URL   AGE   CONDITIONS   READY     REASON
default         6s    3 OK / 6     Unknown
$ oc get events
LAST SEEN   TYPE      REASON            OBJECT           MESSAGE
11s         Normal    FinalizerUpdate   broker/default   Updated "default" finalizers
5s          Warning   InternalError     broker/default   failed to get contract configuration: failed to resolve Spec.Delivery.DeadLetterSink: services.serving.knative.dev "dlq-service" not found
```

**Exit Criteria**
Info about missing sink service is propagated into broker status.
Also, it would be good to have Events tab on the UI page with Broker (same as for Pod for example).

**Comment by pierDipi** [comment]
Thanks for reporting!

/triage accepted
/area broker
/area channel
