### ISSUE TITLE
Kafka Broker connection refused after 1k calls 

### ISSUE THREAD

**Issue by holoed** [knative-sandbox/eventing-kafka-broker#1831]
**Describe the bug**
kafka-broker-ingress stops responding after being called 1k times. (CONNECTION REFUSED)

 **Expected behavior**
Expected to be able to hit Kafka Broker URL with as many requests as possible without it crashing.

 **To Reproduce**
Knative service sending 5k cloud events to Kafka-Broker starts misbehaving around 1k, then after a few seconds it seems to pickup again but then fails again.

 **Knative release version**
Knative Serving 1.2.0
Knative Eventing 1.2.0
Kafka Broker 1.2.0

 **Additional context**
I tried with a 500ms sleep in between the calls to the broker, it still misbehaves after a few thousands.

**Comment by pierDipi** [comment]
Hi @holoed, thanks for reporting!

I need more info to reproduce the issue, can you share:
- requests and limits set on the receiver deployment
- receiver pods metrics

**Comment by pierDipi** [comment]
Hi @holoed, I'm investigating the issue, while I'm doing that can you please downgrade to version 1.1.3.?
