### ISSUE TITLE
Missing configmap error 

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#1910]
When the `channel-controller` is _disabled_ on the controller display

```shell
  Warning  FailedMount  28s (x7 over 91s)  kubelet            MountVolume.SetUp failed for volume "kafka-channel-channels-subscriptions" : configmap "kafka-channel-channels-subscriptions" not found
```

## Version
Knative 1.2.x and later

**Comment by matzew** [comment]
This happens on both dataplane components, for `receiver` and `dispatcher`

**Comment by pierDipi** [comment]
I think this is expected because it doesn't make sense to have the channel data plane installed with the controller disabled, right?

**Comment by matzew** [comment]
I guess, yes.

I had hopes, that I install all `eventing-kafka.yaml` and just disable the controller.

Of course, than why would I do install the deployments for the channel receiver/dispatchers. 

/close
