### ISSUE TITLE
Pass pod names as env var in deployments for logging purposes

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka-broker#192]
**Problem**
With https://github.com/knative/pkg/pull/1714, pod names passed as env vars are used in logging.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
Pod name passed as env vars properly to pods in deployments.

**Time Estimate (optional):**
0.125

**Additional context (optional)**
Ref impl: https://github.com/knative/eventing/pull/4072

**Comment by pierDipi** [comment]
https://github.com/knative-sandbox/eventing-kafka-broker/pull/191
/assign
