### ISSUE TITLE
[Tracking - eventing#4071] Log warning on malformed event in response

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#194]
## Expected Behavior

 - https://github.com/knative/eventing/issues/4071

## Actual Behavior

- We don't log anything.

## Steps to Reproduce the Problem

- https://github.com/knative/eventing/issues/4071

## Additional Info

cc @slinkydeveloper 

/kind enhancement

**Comment by slinkydeveloper** [comment]
I'm not sure we're affected from this problem at all

**Comment by pierDipi** [comment]
This is what we do:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/f802b751f450a4970ee927672c469e1d9fee1dbb/data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java#L62-L84

Can you explain why not?

**Comment by slinkydeveloper** [comment]
We should not, we just need to follow what eventing does

**Comment by pierDipi** [comment]
Eventing returns 502 since 502 is not 2xx the dispatcher retries if there are retries configured, so we need to return a `failedFuture` so that we don't commit the message to Kafka or when we'll retries we can retry as well.
