### ISSUE TITLE
Missing resource limits for data-plane components required for scaling

### ISSUE THREAD

**Issue by aslom** [knative-sandbox/eventing-kafka-broker#1942]
**Describe the bug**
Missing resource limits (CPU and memory) for data-plane components required for scaling.
Without resource limits data-plane components get whatever CPU and memory node has available and performance is unpredicatable and they can even crash ....

 **Expected behavior**
Resource limits are set for data-plane componets for 

```
k -n knative-eventing get po kafka-* |  -oyaml |grep resource
```

 **To Reproduce**
Deploy current version.

 **Knative release version**
v1.2.1

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aslom** [comment]
@pierDipi great to hear it :) I will try testing with those limits

**Comment by pierDipi** [comment]
Thanks for the update, closing
