### ISSUE TITLE
OTEL Distributed Tracing not showing up for Kafka broker and trigger portion 

### ISSUE THREAD

**Issue by zadus** [knative-sandbox/eventing-kafka-broker#1944]
**Describe the bug**
Was following the tracing setup here, [https://knative.dev/blog/articles/distributed-tracing/](url) 
Example was using the default InMemoryChannel prior and the full tracing showed up in jaeger UI, as per the example. 

Tracing not showing up after changing over to Kafka broker and trigger
![sampleHeartBeatHTTP](https://user-images.githubusercontent.com/30067975/155500446-67bfe70f-0863-40a5-8bba-72109f700aba.PNG)

 **Expected behavior**
Full end to end tracing, similar to the example with inMemoryChannel
![image](https://user-images.githubusercontent.com/30067975/155505688-6b7e101e-48f9-4c0a-8226-3c88f1496b86.png)

 **To Reproduce**
Kafka was setup using strimzi operator, 
Kafka Broker setup using steps here [https://knative.dev/docs/eventing/broker/kafka-broker/#installation](url) 
Tracing setup (otel collector, jaeger UI) was followed fully from  [https://knative.dev/blog/articles/distributed-tracing/](url) 

**Knative release version**
Knative v 1.2
Used the latest eventing-kafka-broker, knative-v1.2.3

 **Additional context**
Have tried using zipkin collector as well, having the same issue (IMC tracing appears, but not kafka components)
Saw #1546 , Not sure if this is the solution to the issue I'm facing. Tried updating the configmap and added heads-format with value b3, but did not seem to work. 

Maybe I'm doing something wrong, any help will be appreciated

**Comment by zadus** [comment]
hi @pierDipi , have restarted all the kafka deployments using kubectl rollout restart, and the kafka traces are appearing as expected.

Thanks alot, much appreciated!

**Comment by pierDipi** [comment]
Thanks for the update, closing
