### ISSUE TITLE
Kafka Source Dispatcher crashing

### ISSUE THREAD

**Issue by niels-busch-maersk** [knative-sandbox/eventing-kafka-broker#1948]
**Describe the bug**
Kafka Source Dispatcher goes in to status `CrashLoopBackOff`.

 **Expected behavior**
When I install Kafka source I expect it to not crash, but have status `Running`.

 **To Reproduce**
Use `kn quickstart kind` or `kn quickstart minikube`
Install Kafka controller and Kafka source v.1.2.3 (Also occurs with v1.2.0)
`kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.3/eventing-kafka-controller.yaml`
`kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.3/eventing-kafka-source.yaml`

 **Knative release version**
v1.2.0

 **Additional context**
Log output from the pod:
`{"@timestamp":"2022-02-26T13:31:38.116Z","@version":"1","message":"Failed to startup the dispatcher","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.main.Main","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"java.io.IOException: Function not implemented\n\tat java.base/sun.nio.fs.LinuxWatchService.<init>(Unknown Source)\n\tat java.base/sun.nio.fs.LinuxFileSystem.newWatchService(Unknown Source)\n\tat dev.knative.eventing.kafka.broker.core.file.FileWatcher.start(FileWatcher.java:88)\n\tat dev.knative.eventing.kafka.broker.dispatcher.main.Main.main(Main.java:122)\n"}`

**Comment by niels-busch-maersk** [comment]
I'm using MacBook with M1 processor. I think that could be the reason.

**Comment by pierDipi** [comment]
Hi @niels-busch-maersk, thanks for reporting!

Yes, unfortunately, images aren't multi-arch as reported in https://github.com/knative-sandbox/eventing-kafka-broker/issues/1908.
