### ISSUE TITLE
Support ResetOffset CRD provided by Kafka eventing

### ISSUE THREAD

**Issue by jhill072** [knative-sandbox/eventing-kafka-broker#1949]
**Problem**
The `eventing-kafka` repository has provided support for the custom resource [ResetOffset](https://github.com/knative-sandbox/eventing-kafka/issues/588), allowing the use of a Kubernetes resource to drive the steps necessary to perform the reset of a consumer's offsets. They also left the door open for discovering the provider of a consumer group name (such as the `Trigger` provided here), so I think the broker should have all of the necessary dependency updates to support this.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Event Consumer (I want to replay/skip messages)

**Exit Criteria**
I can create a resource following the [specs from eventing-kafka](https://github.com/knative-sandbox/eventing-kafka/blob/main/config/command/resetoffset/README.md), which results in the setting of the offsets owned by a referenced `Trigger` to be set to earliest/latest/a particular time (depending on the provided value)

**Time Estimate (optional):** 
From my ten minutes of research, I'm expecting this to be a new reconciler, along with potential changes to the dispatcher depending on path of solution.

**Additional context (optional)**
Why do we want to reset offsets?
* To replay messages (instead of shoveling from a dead letter topic)
* To skip poisoned messages (since Kafka topics are read-only)

Process for resetting offsets for a particular consumer group in Kafka:
* Deactivate all consumer instances belonging to the group subscribed to the topic(s) being reset
* Perform the reset offset command for the group id (and topics)
* Reactive the consumers

**Comment by VikramVuppla** [comment]
@pierDipi this looks like a very important feature, any reason this feature was not implemented, can we reopen and prioritize this issue

**Comment by pierDipi** [comment]
/reopen

> @pierDipi this looks like a very important feature, any reason this feature was not implemented, can we reopen and prioritize this issue
>

We don't have capacity to work on it.
 
> in the meantime, is there a way to programmatically stop the consumer groups to reset the offset(as stopping the running consumers is a pre-requisite for resetting the consumer group offset)

Currently, this is only possible with KafkaSource by scaling it to 0, and this will be available for Trigger and Subscription API in future releases as part of #1537
