### ISSUE TITLE
Migrate addressable addresses to use host-based routing instead of a path

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#1951]
**Problem**

Path-based routing leaks implementation details that users shouldn't care about.
This is also a problem for DomainMapping users as reported in https://github.com/knative/serving/issues/12686

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
- Event producer
- System Administrator

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
15

**Additional context (optional)**

/area broker
/area sink
/kind feature-request

**Comment by matzew** [comment]
For the current channel implementation we are also using the `path` approach in this repo

```bash
k get kafkachannel -A 
NAMESPACE   NAME                READY   REASON   URL                                                                                         AGE
default     kafka-channel-one   True             http://kafka-channel-ingress.knative-eventing.svc.cluster.local/default/kafka-channel-one   3m13s

```
