### ISSUE TITLE
Add a test based on the `DeadLetterSinkGenericChannel` feature

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#2002]
**Problem**

Similar to the `TestChannelDeadLetterSink` test, we should create an additional test that uses the `DeadLetterSinkGenericChannel` function instead of `DeadLetterSink`

Example:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/c3ba96be7bd4de07c2d66c98f4a699578e798e3e/test/e2e_new_channel/kafka_channel_upstream_test.go#L213-L234

**Exit Criteria**

A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1

**Additional context (optional)**

/priority important-soon
/area channel
/area test
/good-first-issue

**Comment by GetRohitansh** [comment]
@pierDipi, I have created similar test just by replacing DeadLetterSink function with DeadLetterSinkGenericChannel function, how should I know that it is working now, as I am beginner in this.
Or should I just raise PR
