### ISSUE TITLE
Standalone KafkaSource

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka-broker#2046]
**Problem**
It's not possible to just deploy the KafkaSource controller.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Operator

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

An artifact containing only the KafkaSource controller/CRD

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
<1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by aavarghese** [comment]
...and only create schedulers for those deployed controllers https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/consumergroup/controller.go#L94-L98

**Comment by pierDipi** [comment]
+1, though I'd like to keep the same `kafka-controller` super bundle, can we create an additional main for the controller and perhaps a new artifact with only the source controller and data plane? `eventing-kafka-source-bundle.yaml`?
