### ISSUE TITLE
Resource clean up of auto generated consumer groups

### ISSUE THREAD

**Issue by aavarghese** [knative-sandbox/eventing-kafka-broker#2087]
**Problem**
Consumer groups are created if not specified when a new Kafka source is created; however if the source is later deleted this automatically consumer group is not removed.

Expected behavior
Removing kafasource that had no consumer group specified should remove the auto generated consumer group

References: https://github.com/knative-sandbox/eventing-kafka/issues/839

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

/area source
/area data-plane

**Comment by pierDipi** [comment]
@aavarghese do you have capacity to work on this?
