### ISSUE TITLE
Build fails with sed error in MacOS

### ISSUE THREAD

**Issue by aslom** [knative-sandbox/eventing-kafka-broker#2137]
**Describe the bug**
Build fails with sed error in MacOS

Example

```
============================
==== Fri Apr 29 06:35:03 PDT 2022
============================
Dispatcher image ---> docker.io/aslom/knative-kafka-broker-dispatcher:1728ce5c5b71ef0272b48fc61a5ab0363b72ad6f4049c0d3ed4be118b4502385
Receiver image   ---> docker.io/aslom/knative-kafka-broker-receiver:6b977181a9e1a32b00c8780bebf194d62d4dcd870edce52025ce1bd55a914a87
sed: 1: "eventing-kafka-source.yaml": invalid command code e
ERROR: Failed to set up data plane components
***************************************
***         E2E TEST FAILED         ***
***    Start of information dump    ***
***************************************
```

 **Expected behavior**
Build works

 **To Reproduce**
On MacOS

```
 ./hack/run.sh deploy 
```

 **Knative release version**
1.4

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aslom** [comment]
As suggested @aavarghese the workaround is to deal with differences in sed
https://stackoverflow.com/questions/19456518/error-when-using-sed-with-find-command-on-os-x-invalid-command-code

by changing `hack/data-plane.sh`


```bash
function replace_images() {
  local file=$1
  if [[ $OSTYPE == 'darwin'* ]]; then
    sed -i '' "s|\${KNATIVE_KAFKA_DISPATCHER_IMAGE}|${KNATIVE_KAFKA_DISPATCHER_IMAGE}|g" "${file}" &&
      sed -i '' "s|\${KNATIVE_KAFKA_RECEIVER_IMAGE}|${KNATIVE_KAFKA_RECEIVER_IMAGE}|g" "${file}"
  else
    sed -i "s|\${KNATIVE_KAFKA_DISPATCHER_IMAGE}|${KNATIVE_KAFKA_DISPATCHER_IMAGE}|g" "${file}" &&
      sed -i "s|\${KNATIVE_KAFKA_RECEIVER_IMAGE}|${KNATIVE_KAFKA_RECEIVER_IMAGE}|g" "${file}"
  fi
  return $?
}

```

**Comment by matzew** [comment]
yeah, `sed` is fun on different operating systems

**Comment by pierDipi** [comment]
This is a better solution
https://github.com/knative-sandbox/eventing-kafka-broker/blob/47eb7f496f6fbc86599a5a0ce5f7b69196724e8a/test/e2e-common.sh#L29-L33
we should move that into a top-level imported script.

**Comment by aslom** [comment]
AFAICT `gsed` need to be installed with brew (or some other way) so we would need to add check that is available? sed is always available AFAIK
https://unix.stackexchange.com/questions/390040/gsed-command-not-found-on-macos-with-homebrew

**Comment by aslom** [comment]
@pierDipi proposed PR to fix it https://github.com/knative-sandbox/eventing-kafka-broker/pull/2174
