### ISSUE TITLE
kafka sink: topic is not present

### ISSUE THREAD

**Issue by hehe04** [knative-sandbox/eventing-kafka-broker#2178]
**Describe the bug**

I want to use kafka sink to push app access logs to kafka topic, I deployed crd kafkasink, but I get an error: `topic is not present` . I can confirm that the bootstrap server and the topic are correct. What should I do?

Knative version: v0.24.0
Kafka version : 0.10.1.0

**Comment by pierDipi** [comment]
Hi @hehe04, is it possible for you to try a more recent version of Knative?

It might be also related to the use of Kafka 0.10, but without a minimal reproducer that I can just execute, it is hard for me to reproduce.

**Comment by hehe04** [comment]
Hi @pierDipi , thanks for yor reply.  I solved the problem after upgrading the Kafka version to 2.4, it seems that it does not support older versions of kafka.  suggest to add the minimum version of Kafka supported  to the require list
