### ISSUE TITLE
Unacceptable duplicate events from dispatcher to sink 

### ISSUE THREAD

**Issue by steven0711dong** [knative-sandbox/eventing-kafka-broker#2202]
**Describe the bug**
When running Kafka source and sink receiving events, we encountered unacceptable number of duplicate events. 

 **Expected behavior**
Although dups are unavoidable but the number of duplicate events is too many. See my results below:

Testing with no delay, 3000 events result 
source stevensource received: 3000 messages, 0 are dups and 0 non 200s.
Testing with no delay, 5000 events result 
source stevensource received: 5000 messages, 0 are dups and 0 non 200s.
**Testing with no delay, 20000 events result 
source stevensource received: 28000 messages, 8081 are dups and 0 non 200s.
Testing with 3 seconds delay with 2000 events result 
source stevensource received: 2000 messages, 1045 are dups and 0 non 200s.
Testing with 3 seconds delay with 10000 events result 
source stevensource received: 10000 messages, 8106 are dups and 0 non 200s.**

 **To Reproduce**
Create a Kafka source and make a sink that delays for 3-5 seconds, send large number of events to keep Kafka client consumer running for more than 15-20 mins and you should see dups in sink. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aslom** [comment]
Do you know what is causing increase of duplicates? Is there timeout with event delivery to sink if it takes too long to return response? What happens if sink sleep time is very large?  >3600 seconds?

**Comment by steven0711dong** [comment]
I think I get a better understanding of the dups problem now. You can also use this scenario to reproduce the dups problem. Send to a topic with 50 partitions 3000 events and observe the number of event received in the first dispatcher pod. You will see that those 3000 events immediately get consumed and those events just stays in memory waiting to be sent to sink. However, at this time, the events are still not committed yet so by the time other dispatcher pods came up, some of the previous events are re-consumed. This is why dups are happening. I don't think the dispatcher should consume 3000 events immediately and just keep them in memory, what if we sent 6000 or even 10 million events. This absolutely kills memory. @aslom @aavarghese

**Comment by steven0711dong** [comment]
> Do you know what is causing increase of duplicates? Is there timeout with event delivery to sink if it takes too long to return response? What happens if sink sleep time is very large? >3600 seconds?

I don't know the answer to this question. I can only say that the dups seem to correlate to the length of sink delay.

**Comment by pierDipi** [comment]
Please, provide a minimal reproducer or an e2e test that we can just apply and see the results/debug the issue, thanks!

**Comment by aavarghese** [comment]
Additional thing to do post WG meeting:
Try to change `partition.assignment.strategy` from default `RangeAssignor` to something more sticky and incremental like `org.apache.kafka.clients.consumer.CooperativeStickyAssignor` to reduce dups (Separate PR?)

cc @pierDipi @steven0711dong @aslom @matzew

**Comment by steven0711dong** [comment]
Since the merge of rate limiter PR and the PR for discarding messages upon partition revoke, I re-tested the Kafka source. We do see significant reduce amount of duplicate events, but the mitigation of event dups is not optimal enough. Please see the test results. 
Before the fix of these 2 PRs. This is without the pre-scale of consumers: 
```
Testing with 3 seconds delay with 10000 events result 
source stevensource received: 10000 messages, 8106 are dups and 0 non 200s.
```
After the fix of these 2 PRs. This is also without the pre-scale of consumers
```
source stevensource received: 10000 messages, 512 are dups and 0 non 200s.
```
Imo, going from 8106 dups to 512 is a significant improvement, however, I don't think the users are ok with also 5% of their events are duplicated.
