### ISSUE TITLE
Kafka client halts and gets into stucked state 

### ISSUE THREAD

**Issue by steven0711dong** [knative-sandbox/eventing-kafka-broker#2218]
**Describe the bug**
When a Kafka client is run for the same topic and consumer group across on multiple machines, occasionally, the Kafka client on one of the machine is halted and no longer consumes event. One has to kill pod so the client could be un-stucked. 

 **Expected behavior**
Kafka client should auto rebalance and event consumption should continues on without being in a stuck state. 

 **To Reproduce**
There is no exact steps to re-produce the issue because this happens occasionally. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by pierDipi** [comment]
I need more information and logs on when this happens.

This command gives us the active consumers for all groups:
```
kubectl -n kafka run kafka-consumer -ti --image=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0 --rm=true --restart=Never -- bin/kafka-consumer-groups.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --describe --all-groups
```
and we need logs from all kafka-source-dispatcher pods
