### ISSUE TITLE
Opened CircuitBreaker causes all events to go to DeadLetterSink

### ISSUE THREAD

**Issue by apenen** [knative-sandbox/eventing-kafka-broker#2239]
Hi,

When CircuitBreaker is opened it produces OpenCircuitException,  sender treats it as failure and then the event is sent to DLS.
This can be improved if sender waits for CircuitBreaker to be closed, before processing more events. This events should be queued in kafka until CircuitBreaker closes.

**Comment by pierDipi** [comment]
We have removed the circuit breaker because it wasn't programmable for users and this hidden behavior you're highlighting was more confusing than useful.
