### ISSUE TITLE
Expose Prometheus metrics

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#227]
**Problem**

[Broker spec](https://github.com/knative/eventing/blob/master/docs/spec/broker.md#observability):
> The Broker SHOULD expose a variety of metrics, including, but not limited to:
>
> Number of malformed produce requests (400-level responses)
>Number of accepted produce requests (200-level responses)
> Number of events delivered
>
> Metrics SHOULD be enabled by default, with a configuration parameter included to disable them if desired.

[Channel spec:](https://github.com/knative/eventing/blob/master/docs/spec/channel.md#metrics)

> Channels SHOULD expose a variety of metrics, including, but not limited to:
>
> Number of malformed incoming event queueing events (400 Bad Request responses)
> Number of accepted incoming event queuing events (202 Accepted responses)
> Number of egress CloudEvents produced (with the former metric, used to derive channel queue size)
>
>Metrics SHOULD be enabled by default, with a configuration parameter included to disable them if desired.

- Notes: 
  > Metrics support. Currently, there is no shared format that could be used to test support for metrics.

**Exit Criteria**

Metrics are exposed by data plane pods.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
3

**Additional context (optional)**

#### Design

- Number of malformed produce requests (400-level responses) or Number of malformed incoming event queueing events (400 Bad Request responses)
  - `name` :arrow_right: `http_requests_malformed_total`
- Number of accepted produce requests (200-level responses)
   - `name` :arrow_right: `http_requests_produce_total`
- Number of events delivered or Number of egress CloudEvents produced
  - `name` :arrow_right: `http_events_sent_total`

- In addition to spec metrics, we export [`Vertx` core metrics](https://vertx.io/docs/vertx-micrometer-metrics/java/#_vert_x_core_tools_metrics)

- > Metrics SHOULD be enabled by default
  
  Unclear how to disable them. This needs probably an upstream discussion.

- For now, we don't expose [`JVM` related metrics](https://vertx.io/docs/vertx-micrometer-metrics/java/#_jvm_or_other_instrumentations)

### Testing

We can scrape data plane pods and create assertions based on a regex (or feel free to propose another option).

/area data-plane
/kind feature-request
/assign

cc @slinkydeveloper

**Comment by slinkydeveloper** [comment]
I don't think the exit criteria should be an e2e for the metrics. For that, let's wait some progress on eventing first. For the rest, i'm fine and super pumped for this one!
