### ISSUE TITLE
Failed events are not enhanced with extension attributes

### ISSUE THREAD

**Issue by egorlepa** [knative-sandbox/eventing-kafka-broker#2340]
**Describe the bug**
Failed events are not enhanced with extension attributes prior to forwarding to the deadLetterSink as described here: 
https://knative.dev/docs/eventing/event-delivery/#configuring-channel-event-delivery
(knativeerrordest, knativeerrorcode, knativeerrordata) 

 **Expected behavior**
I expect failed events to be enhanced with extension attributes.

 **Knative release version**
1.5

 **Additional context**
Sending event to deadLetterSink is kind of pointless without some context (where this event was meant to be delivered; what happened). There is not really much i can do with such event - i don't know which subscriber failed to consume it and why

**Comment by pierDipi** [comment]
Hi @egorlepa, thanks for reporting!

I agree that we should add this feature to this implementation but I'm not entirely sure about the `knativeerrordata`, the `body` might be very large and it might not fit into a header.

I'll discuss this with the group (you're very welcome to join) because I don't think the data can be included in this way.

**Comment by egorlepa** [comment]
hey, @pierDipi i believe default channel implementation can be used as a reference. it defines max body size as 1024 bytes, everything else gets truncated.
https://github.com/knative/eventing/blob/release-1.5/pkg/channel/attributes/knative_error.go

**Comment by egorlepa** [comment]
Please, consider also adding information about sender (broker name/channel name/something like that). I am trying to create a single entry point for failed events and such information would help.

**Comment by pierDipi** [comment]
you can reach out to us with these methods https://knative.dev/docs/community/contributing/#learn-and-connect or just with comments on this issue if you don't want to create accounts or join groups, etc.

We also run a meeting, Eventing Kafka WG, on Tuesday every other week, you can find it in this shared calendar https://calendar.google.com/calendar/u/0/embed?src=knative.team_9q83bg07qs5b9rrslp5jor4l6s@group.calendar.google.com&ctz=America/Los_Angeles

**Comment by matzew** [comment]
@egorlepa Are you interested in tackling this?

You can reach us on the resources that Pierangelo mentioned :smile:

**Comment by egorlepa** [comment]
Yeah, sorry, last 2 weeks were very tough. I'll have time this week, also I joined slack
