### ISSUE TITLE
Release notes for 0.18

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#240]
There are no release notes for 0.18, see diff: https://github.com/knative-sandbox/eventing-kafka-broker/compare/v0.17.0...v0.18.0 and respective PRs.

**Comment by pierDipi** [comment]
cc @slinkydeveloper

**Comment by slinkydeveloper** [comment]
I don't have rights to modify them, do you have them?

**Comment by pierDipi** [comment]
Ok, I think we can put together a markdown message and ping Scott, he should be happy to help us! :wink: 

/assign

**Comment by pierDipi** [comment]
## New features

- You can stream HTTP CloudEvents into Apache Kafka using `KafkaSink` objects: ([#177](https://github.com/knative-sandbox/eventing-kafka-broker/pull/177), [#134](https://github.com/knative-sandbox/eventing-kafka-broker/pull/134), [@pierDipi](https://github.com/pierDipi))
- Now you can configure the [server options:](https://vertx-web-site.github.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html), modifying the config map `config-kafka-broker-data-plane` ([#151](https://github.com/knative-sandbox/eventing-kafka-broker/pull/151), [@slinkydeveloper](https://github.com/slinkydeveloper))
- Now you can configure the [web client options](https://vertx-web-site.github.io/docs/apidocs/io/vertx/ext/web/client/WebClientOptions.html), modifying the config map `config-kafka-broker-data-plane` ([#149](https://github.com/knative-sandbox/eventing-kafka-broker/pull/149), [@slinkydeveloper](https://github.com/slinkydeveloper))

## Actions required (pre-upgrade): 

  - Allow independent installation of components ([#176](https://github.com/knative-sandbox/eventing-kafka-broker/pull/176), [@pierDipi](https://github.com/pierDipi))
    - Remove `kafka-broker-controller`
      - `kubectl delete -n knative-eventing deployment kafka-broker-controller`
      - `kubectl delete -n knative-eventing clusterrolebindings.rbac.authorization.k8s.io kafka-broker-controller`
      - `kubectl delete -n knative-eventing clusterrolebindings.rbac.authorization.k8s.io kafka-broker-addressable-resolver`
      - `kubectl delete -n knative-eventing clusterroles.rbac.authorization.k8s.io kafka-broker-controller`
      - `kubectl delete -n knative-eventing serviceaccounts kafka-broker-controller`
    - Remove `kafka-broker-config-logging` (post-upgrade) 
      - `kubectl delete -n knative-eventing cm kafka-broker-config-logging` 

## Fix bug 
  - Update Broker and Trigger status when there is a failure. ([#157](https://github.com/knative-sandbox/eventing-kafka-broker/pull/157), [@pierDipi](https://github.com/pierDipi))


---

Row markdown :arrow_down: 

```
## New features

- You can stream HTTP CloudEvents into Apache Kafka using `KafkaSink` objects: ([#177](https://github.com/knative-sandbox/eventing-kafka-broker/pull/177), [#134](https://github.com/knative-sandbox/eventing-kafka-broker/pull/134), [@pierDipi](https://github.com/pierDipi))
- Now you can configure the [server options:](https://vertx-web-site.github.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html), modifying the config map `config-kafka-broker-data-plane` ([#151](https://github.com/knative-sandbox/eventing-kafka-broker/pull/151), [@slinkydeveloper](https://github.com/slinkydeveloper))
- Now you can configure the [web client options](https://vertx-web-site.github.io/docs/apidocs/io/vertx/ext/web/client/WebClientOptions.html), modifying the config map `config-kafka-broker-data-plane` ([#149](https://github.com/knative-sandbox/eventing-kafka-broker/pull/149), [@slinkydeveloper](https://github.com/slinkydeveloper))

## Actions required (pre-upgrade): 

  - Allow independent installation of components ([#176](https://github.com/knative-sandbox/eventing-kafka-broker/pull/176), [@pierDipi](https://github.com/pierDipi))
    - Remove `kafka-broker-controller`
      - `kubectl delete -n knative-eventing deployment kafka-broker-controller`
      - `kubectl delete -n knative-eventing clusterrolebindings.rbac.authorization.k8s.io kafka-broker-controller`
      - `kubectl delete -n knative-eventing clusterrolebindings.rbac.authorization.k8s.io kafka-broker-addressable-resolver`
      - `kubectl delete -n knative-eventing clusterroles.rbac.authorization.k8s.io kafka-broker-controller`
      - `kubectl delete -n knative-eventing serviceaccounts kafka-broker-controller`
    - Remove `kafka-broker-config-logging` (post-upgrade) 
      - `kubectl delete -n knative-eventing cm kafka-broker-config-logging` 

## Fix bug 
  - Update Broker and Trigger status when there is a failure. ([#157](https://github.com/knative-sandbox/eventing-kafka-broker/pull/157), [@pierDipi](https://github.com/pierDipi))
```

@n3wscott, could you please update the release notes? :pray: 

/assign @n3wscott

**Comment by pierDipi** [comment]
I used this tool to generate release notes: https://github.com/kubernetes/release/tree/master/cmd/release-notes. 
They require some manual adjustments but at least it automates the boring stuff.

**Comment by n3wscott** [comment]
Thanks so much! Updated.
/close
