### ISSUE TITLE
Upgrade test wathola receiver reports missing event but the event was received

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#2427]
**Describe the bug**

In https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/1417/upgrade-tests_eventing-kafka-broker_main/1552553233526820864, the reports says:

```
event #23341 should be received once, but was received 0 times
```

by downloading and viewing the [trace](https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/1417/upgrade-tests_eventing-kafka-broker_main/1552553233526820864/artifacts/04056064-0e45-11ed-bb1d-ea88fc77f242/traces/events/step-23341.json) as described in https://github.com/knative/eventing/tree/main/test/upgrade#inspecting-zipkin-traces-for-undelivered-events, I see that the event was received successfully (200):

![image](https://user-images.githubusercontent.com/33736985/181452068-ee47826f-31db-4be1-9416-3292d12f8a68.png)

 **Expected behavior**

Test passes reliably.

 **To Reproduce**

Run upgrade test, in particular KafkaSource and KafkaSink continuous tests.

 **Knative release version**

`devel`

 **Additional context**

/priority important-soon

**Comment by pierDipi** [comment]
@cardil @mgencur is this something you might help with?

**Comment by cardil** [comment]
From log:

```
prober.go:106: event #23341 should be received once, but was received 0 times
prober.go:106: event #23342 should be received once, but was received 0 times
prober.go:106: event #23343 should be received once, but was received 0 times
prober.go:106: event #23344 should be received once, but was received 0 times
prober.go:106: expecting to have 23344 unique events received, but received 23340 unique events
```

So, those were the last 4 events, which are missing. This smells to me like a closing/termination problem. 

We've got similar issues in the past, for ex.: https://github.com/knative/eventing/issues/6330. The past issues were the other way around, the events were delivered, but the spans were not published to span store (no proper clean-up of Zipkin exporter https://github.com/knative/eventing/pull/6331). This time we have missing events, but spans are published?!? Very strange, indeed.

I could take a look at this further after PTO. Maybe @mgencur could look at this sooner...

**Comment by mgencur** [comment]
This is strange, yeah.
I can see in the "sender" log that the last event being logged is 23326:
```
{"level":"info","ts":"2022-07-28T07:42:51.708312938Z","caller":"sender/services.go:227","msg":"Sending step event #23326 to \"http://kafka-sink-ingress.knative-eventing.svc.cluster.local/eventing-e2e13/sink-kafka-sink-source-continual-test\""}
```
However, it doesn't explain it. It only makes it more strange.

**Comment by pierDipi** [comment]
I think I might know what's wrong, the receiver just stops collecting events when it receives the `FinishedType` event, however, for partitioned topics like Kafka that doesn't mean that we have consumed all partitions, but it just means that the partition that contains that event type has been consumed fully, so other partitions might still contain other events that will be reported as missing and they will be received shortly after but still reported as missing.

**Comment by pierDipi** [comment]
We cannot assume total ordering in the upgrade test.

**Comment by pierDipi** [comment]
@mgencur @cardil is that what roughly might be happening here?

**Comment by mgencur** [comment]
@pierDipi That sounds about right.
