### ISSUE TITLE
when trigger restart,history event also load in

### ISSUE THREAD

**Issue by momochaasdf** [knative-sandbox/eventing-kafka-broker#2553]
step:
1. A service listen a trigger
2. when delete event happend, A service can receive delete event
3. restart A service, also restart trigger, in A service logs, we can find old delete event is listened
we want old event cloud not be listened, how to config it?

**Comment by momochaasdf** [comment]
version:v1.6.3

**Comment by momochaasdf** [comment]
![image](https://user-images.githubusercontent.com/18320263/186337008-bc55a497-8d6b-4b89-85eb-21009e7f0988.png)

**Comment by momochaasdf** [comment]
every time helm chart uninstall and install, the same old event will be listened,
how to do, only listen the new event?

**Comment by pierDipi** [comment]
@momochaasdf if uninstalling the chart causes the trigger to be removed, then installing it again will create a new trigger with the original lifecycle.

To receive only new events you can set [auto.offset.reset=latest](https://github.com/knative-sandbox/eventing-kafka-broker/blob/f2dbfa1788bbec0b84763a8c4e0d336696081db0/data-plane/config/broker/100-config-kafka-broker-data-plane.yaml#L126) in the `config-kafka-broker-data-plane`

**Comment by momochaasdf** [comment]
![image](https://user-images.githubusercontent.com/18320263/188771099-19d9534b-dd5d-4dbb-980c-42527e3a7198.png)
yes,we find it.
update this property value to latest is all right?
thank you very much.

**Comment by pierDipi** [comment]
Yes, after the update you need to restart the dispatcher
```shell
kubectl rollout restart deployment -n knative-eventing kafka-broker-dispatcher
```

**Comment by momochaasdf** [comment]
ok,thank you very much.
