### ISSUE TITLE
Using Knative Kafka broker, Knative serving does not create more than 8 pods

### ISSUE THREAD

**Issue by xuanhai266** [knative-sandbox/eventing-kafka-broker#2597]
**Describe the bug**
Knative configuration as below:
- Source: AWS SQS source
- Broker: Kafka broker
- Trigger: A trigger with sink is a Knative service
- Knative service: A knative service with `containerConcurrency = 1` (to make sure 1 request/pod at a time)
  
Send a lot of messages to SQS queue, Knative service only creates maximum 8 pods to process all requests and all requests come to 1 or 2 pods only.

 **Expected behavior**
- Knative service creates a ton of pods (more than 8) to process all requests and requests come to some pods

 **To Reproduce**
Knative configuration as below:
- Source: AWS SQS source with sink is kafka broker
- Broker: Kafka broker with a Kafka cluster
- Trigger: A trigger with source is Kafka broker and sink is a Knative service
- Knative service: A knative service with `containerConcurrency = 1` (to make sure 1 request/pod at a time)

Send 20-100 messages to SQS queue and wait for Knative Service creating pods.

 **Knative release version**
1.6.0
 **Additional context**
If use MTchannelbased broker (with InMemoryChannel) instead of Kafka broker, this problem does not occur, Knative Service can create about 10-20 pods to process 20 requests.

**Comment by pierDipi** [comment]
Hi @xuanhai266 thanks for reporting, this should be fixed in 1.6.5 and 1.7.0, can you please try any of them?

**Comment by xuanhai266** [comment]
> Hi @xuanhai266 thanks for reporting, this should be fixed in 1.6.5 and 1.7.0, can you please try any of them?

Thank you for your reply.
I tried with v1.7.0 and this problem does not occur anymore.
I seems to be that it was already fixed in v1.7.0 but I'm not sure it's correct or not (because it is not mentioned in the changelogs of v1.7.0).

**Comment by pierDipi** [comment]
Yes, it is fixed in both 1.7.0 and 1.6.5.

closing the issue, please reopen if that's not the case for you.

**Comment by xuanhai266** [comment]
I have a concern point.  
With v1.7.0, when I send 1000 messages to AWS SQS, Kafka broker only sends about 100-180 events to Knative Service at once.
Thus, Knative service only creates about 1xx pods to handle these events.  
The remaining events will be failed to send to Knative service and broker will retry sending.  
Is there any configuration in Kafka broker to increase number of events that will be sent to Knative service at once?  
FYI: With MTchannelbased broker (in-memory channel), it can send 400-1000 events to Knative service at once.

**Comment by pierDipi** [comment]
you can increase to get more inflight records:
- `max.poll.records` https://github.com/knative-sandbox/eventing-kafka-broker/blob/f5f44480ab4a8165fbfe522cc72f741628c1f60d/data-plane/config/broker/100-config-kafka-broker-data-plane.yaml#L135
- `maxPoolSize` https://github.com/knative-sandbox/eventing-kafka-broker/blob/f5f44480ab4a8165fbfe522cc72f741628c1f60d/data-plane/config/broker/100-config-kafka-broker-data-plane.yaml#L178

**Comment by xuanhai266** [comment]
> you can increase to get more inflight records:
> 
> * `max.poll.records` https://github.com/knative-sandbox/eventing-kafka-broker/blob/f5f44480ab4a8165fbfe522cc72f741628c1f60d/data-plane/config/broker/100-config-kafka-broker-data-plane.yaml#L135
> * `maxPoolSize` https://github.com/knative-sandbox/eventing-kafka-broker/blob/f5f44480ab4a8165fbfe522cc72f741628c1f60d/data-plane/config/broker/100-config-kafka-broker-data-plane.yaml#L178

Thank you for your suggestion.
It works well.
