### ISSUE TITLE
update developer guide to include tailored k8s cluster installation

### ISSUE THREAD

**Issue by Alfusainey** [knative-sandbox/eventing-kafka-broker#26]
**Problem**

The current developer guide documentation references the main `knative install docs` for instructions on how to create a  k8s cluster for this project. However, the referenced knative docs does not include the creation of k8s clusters and assumes that user's already have one created.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

Contributor

**Comment by Alfusainey** [comment]
@pierDipi any update on this?

**Comment by pierDipi** [comment]
I'm on it

**Comment by pierDipi** [comment]
@Alfusainey can you follow steps described here: https://github.com/knative-sandbox/eventing-kafka-broker/pull/29

**Comment by Alfusainey** [comment]
> @Alfusainey can you follow steps described here: #29?

ok, am on it now
