### ISSUE TITLE
[flaky] Failed to create v1 broker "broker": denied the request: decoding request failed: unhandled kind: eventing.knative.dev/v1, Kind=Broker

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#2612]
**Describe the bug**

Upgrade test is getting:
```
Failed to create v1 broker "broker": admission webhook "validation.webhook.kafka.eventing.knative.dev" denied the request: decoding request failed: unhandled kind: eventing.knative.dev/v1, Kind=Broker
```

 See https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/2601/upgrade-tests_eventing-kafka-broker_main/1567518977649807360

 **Expected behavior**

No errors

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**
`main`

 **Additional context**

- related recent changes in https://github.com/knative-sandbox/eventing-kafka-broker/commit/e5a64380c2e5533a3d85dd5924b3ea1b63c34806

**Comment by pierDipi** [comment]
it might be that the webhook instance that actually responded to the request is for a previous version because the rollout isn't complete yet when we tried to create a broker.

**Comment by aliok** [comment]
Ok, but I don't understand why I didn't get it in my PR that touched the webhook.
