### ISSUE TITLE
[CI error] debconf: delaying package configuration, since apt-utils is not installed

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#274]
## Expected Behavior

No errors in CI.

It's probably related to apt-get package installation:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/af0db9fb3d5764b4a2ce6403422f88bf81d2e5c5/data-plane/docker/Dockerfile#L27-L28

## Actual Behavior

[Error: `debconf: delaying package configuration, since apt-utils is not installed`](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/249/pull-knative-sandbox-eventing-kafka-broker-integration-tests/1314240316777172998#1:build-log.txt%3A1399)

## Steps to Reproduce the Problem

1. Build data plane images

**Comment by pierDipi** [comment]
/reopen

This is still an issue.

https://github.com/knative-sandbox/eventing-kafka-broker/runs/1331294534?check_suite_focus=true#step:9:316

**Comment by slinkydeveloper** [comment]
Well, this is a warning, It doesn't break anything, I think we can ignore it and I'm sure it will go away with newest debian bases

**Comment by pierDipi** [comment]
Agree.

/good-first-issue
