### ISSUE TITLE
Bump Sarama from 1.27.0 to 1.27.2

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#278]
**Problem**

We need to bump the Sarama library, see release notes: https://github.com/Shopify/sarama/releases/tag/v1.27.2

**Exit Criteria**
Bump Sarama from 1.27.0 to 1.27.2

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

There are some breaking changes even if it's a patch release.

/kind feature-request
/good-first-issue

**Comment by sheetalsingala** [comment]
I can work on this!

**Comment by sheetalsingala** [comment]
go version - `go version go1.14.10 linux/amd64`
I did follow the instructions. 
I can update most of the other go modules but I cannot update a few.

**Comment by pierDipi** [comment]
That's weird :thinking:

**Comment by pierDipi** [comment]
There a new version 1.28, I opened a new issue: https://github.com/knative-sandbox/eventing-kafka-broker/issues/661
