### ISSUE TITLE
Generalize and abstract reconcile loops in java code 

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#279]
**Problem**
We now have two object reconciler loops in java code, one in dispatcher and one in receiver, they both use the same logic to perform reconciliation. We can abstract that algorithm

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Kafka Broker developer

**Exit Criteria**
Better code organization of the reconcile loops in dispatcher and receiver

**Time Estimate (optional):** 
1

**Additional context (optional)**
The dispatcher and receiver may just need to implement this interface:

```java
interface ReconcileListener {
  onNewResource()
  onDeletedResource()
  onUpdatedResource()
  onNewEgress()
  onDeletedEgress()
}
```

To perform the operations on specific events

cc @pierDipi 

/assign

**Comment by pierDipi** [comment]
:+1: 

/area data-plane
