### ISSUE TITLE
Broker deletion is stuck when the referenced secret is gone

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#2828]
If using a `auth.secret.ref.name` and if that referenced secret is gone (regardless how it was removed), the deletion of the broker is stuck:

```
k delete -f ./015-broker-with-config.yaml 
broker.eventing.knative.dev "my-broken-kafka-broker" deleted
configmap "my-broken-kafka-broker-config" deleted
```

Especially in cases with _external_ topics, we should be more lenient, if the secret is not present, and not block the finalization

**Comment by matzew** [comment]
A bit related or similar to this https://github.com/knative-sandbox/eventing-kafka-broker/issues/2536 (but here just for `Secrets`)

**Comment by r00ta** [comment]
Hi @matzew , I remember I faced it in SmartEvents some months ago and we referenced to https://github.com/knative-sandbox/eventing-kafka-broker/issues/2211 . Isnt't the same issue?
