### ISSUE TITLE
Support specifying consumer group id in trigger

### ISSUE THREAD

**Issue by xqianwang** [knative-sandbox/eventing-kafka-broker#3057]
**Problem**
A short explanation of the problem, including relevant restrictions.
We want to give a meaningful name or name like <trigger-name>-<event-type> for consumer group id of created trigger
**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
This is coming in 1.10 (~ this week), see https://github.com/knative-sandbox/eventing-kafka-broker/pull/3033

This is the default template for the group id we will use for _new_ triggers
```
knative-trigger-{{ .Namespace }}-{{ .Name }}
```
but you can change as you wish in the `config-kafka-features` ConfigMap

**Comment by xqianwang** [comment]
> This is coming in 1.10 (~ this week), see #3033
> 
> This is the default template for the group id we will use for _new_ triggers
> 
> ```
> knative-trigger-{{ .Namespace }}-{{ .Name }}
> ```
> 
> but you can change as you wish in the `config-kafka-features` ConfigMap

Hi @pierDipi thanks for reply!

**Comment by pierDipi** [comment]
Release is out: https://github.com/knative-sandbox/eventing-kafka-broker/releases/tag/knative-v1.10.0, feel free to give us feedback on the feature here or on the CNCF slack
