### ISSUE TITLE
Implement KafkaSource controller

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#312]
**Problem**
We need to implement the KafkaSource controller for the data plane in this repo

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Users

**Exit Criteria**
A working kafka source implementation using the data-plane in this project. All e2e tests of kafka source passing.

**Time Estimate (optional):** 
10

**Comment by matzew** [comment]
Interesting, could be aligned w/ the `eventing-kafka` repo? or is that competing ?

**Comment by slinkydeveloper** [comment]
The idea is to reuse the data plane we have here and build the control plane for it. I guess it's mostly competing, because by the nature of this data plane, this implementaiton will be a "multi-tenant" kafka source

**Comment by lionelvillard** [comment]
did you say multi-tenant, as of 1 data-plane component for all source instances? @slinkydeveloper ?

**Comment by slinkydeveloper** [comment]
@lionelvillard yep that's the idea

**Comment by lionelvillard** [comment]
Of course :-) Do you have a design document describing how the scaling works? I'm assuming it's using Keda, but I'm most curious to know how source instances scale independently to each other. @slinkydeveloper

**Comment by pierDipi** [comment]
Roughly the rough idea is to:
- add the number of consumers to run for each KafkaSource or Trigger (Egress in our terminology)
  - how?
     - KafkaSource: scale subresource (your PR) or an annotation
     - Trigger: an internal CRD with the scale subresource or an annotation
- use the `RangeAssignor` to partition consumer instances (your design document) + defining a total order for each Egress config so that each pod has the same view of the system.

**Comment by lionelvillard** [comment]
ah cool thanks!
