### ISSUE TITLE
Eventing TLS: support https in the prober

### ISSUE THREAD

**Issue by Cali0707** [knative-sandbox/eventing-kafka-broker#3128]
**Problem**
The prober currently only supports http. As mentioned in #3122 the prober should support TLS, so that when we have strict transport encryption the prober does not fail.

**Exit Criteria**
A test showing that the prober works with TLS and https addresses.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**
Add any other context about the feature request here.
- Related to #3108 

/good-first-issue

**Comment by pierDipi** [comment]
@Cali0707 as a follow up to this issue, #3123, and #3122 we need to the use the TLS prober since now it's not actually used, can we capture that into an issue?

**Comment by Cali0707** [comment]
> @Cali0707 as a follow up to this issue, #3123, and #3122 we need to the use the TLS prober since now it's not actually used, can we capture that into an issue?

Yep, opening one now, I'll link it here
