### ISSUE TITLE
Implement KafkaChannel controller

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#313]
**Problem**
We need to implement the KafkaChannel controller for the data plane in this repo

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Users

**Exit Criteria**
A working kafka channel implementation using the data-plane in this project. All e2e tests of kafka channel passing (excluding tracing, which is being discussed at #115).

**Time Estimate (optional):** 
3

**Comment by pierDipi** [comment]
For this one, we should start allowing different conditions set for the KafkaChannel like https://github.com/knative/eventing/pull/3545.

**Comment by aliok** [comment]
@pierDipi 

I started working on this. I hope you don't mind that I unassign you.

**Comment by aliok** [comment]
/close

Closing this ticket as it is rather old and not really updated
