### ISSUE TITLE
Release cert-manager certificates in eventing-kafka-tls-networking

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#3155]
**Problem**

In https://github.com/knative-sandbox/eventing-kafka-broker/commit/9e322471ca6ae985fe68380b4609f97f055ca456, we added server certificates Cert-manager resources.

We need to create an artifact (maybe `eventing-kafka-tls-networking.yaml`) that will be released in our release assets (done by script https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/hack/release.sh).

In addition to be released, we need to install Cert-manager with `kubectl apply -f third_party/cert-manager` and apply the new file `eventing-kafka-tls-networking.yaml` during development as part of `hack/run.sh deploy` (before installing our components) https://github.com/knative-sandbox/eventing-kafka-broker/blob/34946a83f98dfab53c81618814e3c4107858148c/test/e2e-common.sh#L207-L228)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
System operator, Contributor

**Exit Criteria**
- `hack/run.sh deploy` creates a file `eventing-kafka-tls-networking.yaml` in the root of the repository and applies it
- `hack/release.sh` publishes `eventing-kafka-tls-networking.yaml`

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

- This is similar to https://github.com/knative/eventing/commit/825a2b595b0ce93026b4bed94526759a17bf2fa2
- https://github.com/knative-sandbox/eventing-kafka-broker/blob/34946a83f98dfab53c81618814e3c4107858148c/hack/release.sh#L70-L84
- https://github.com/knative-sandbox/eventing-kafka-broker/blob/34946a83f98dfab53c81618814e3c4107858148c/test/e2e-common.sh#L207-L228

**Comment by Cali0707** [comment]
@pierDipi our Cert-manager resources depend on https://github.com/knative/eventing/blob/main/config/tls/issuers/selfsigned-ca-issuer.yaml. Should we also include this in our release assets, or is this guaranteed to be in a cluster where someone installs `eventing-kafka-broker`?
