### ISSUE TITLE
[core/dispatcher/receiver][data-plane] Reconciler should live in its own verticle, detached from FileWatcher thread

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#332]
**Describe the bug**
Today we run the reconciler within the `FileWatcher` running thread. This makes weird the listeners and more slippy to implement, because they don't have the same guarantees as running inside `Verticle` (like the single thread guarantee, that allows to use non thread-safe data structures).

 **Expected behavior**
`Reconciler` should run within its own verticle and receive file watch updates from `FileWatcher`

**Comment by pierDipi** [comment]
It's not really a bug.

/remove-kind bug

**Comment by pierDipi** [comment]
Related: https://github.com/knative-sandbox/eventing-kafka-broker/issues/337
