### ISSUE TITLE
[data-plane] Remove Thread.sleep in tests and replace with awaitability or similar

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#351]
**Describe the bug**
We have some tests where we use Thread.sleep. These causes flakyness, we should get rid of these and replace with proper async assertions like awaitability

 **Expected behavior**
Remove Thread.sleep all around our data plane tests

**Comment by OmarMorales71** [comment]
@pierDipi Hello, Could I contribute with this issue? I'm working on it 

/assign

**Comment by slinkydeveloper** [comment]
Sure go ahead!

**Comment by OmarMorales71** [comment]
@slinkydeveloper I'm checking the Awaitility dependency and I would want to know what is the purpose of the Thread.sleep() in the test. Is waiting for what? The question is for choose the best implementation. Thanks :D

**Comment by pierDipi** [comment]
Hi @OmarMorales71!

We have 3 sleep to remove for this issue: https://github.com/knative-sandbox/eventing-kafka-broker/search?q=Thread.sleep

---

This one: https://github.com/knative-sandbox/eventing-kafka-broker/blob/50e92f981fd837b142425965a828f44c56354e93/data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java#L126 is waiting for this condition: https://github.com/knative-sandbox/eventing-kafka-broker/blob/50e92f981fd837b142425965a828f44c56354e93/data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java#L128

---

This one:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/b92bcd9eb938e3daad0e8756387732e34240f411/data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java#L74
can be safely removed.

---

This one https://github.com/knative-sandbox/eventing-kafka-broker/blob/50e92f981fd837b142425965a828f44c56354e93/data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java#L199
is waiting for `numEgresses verticles (= 3) + numResources ( = 1) verticles + system verticle ( = 1) = 5`.
To get the actual number of verticles use `vertx.deploymentsIDs().size()` (it's similar to the first one).

**Comment by OmarMorales71** [comment]
@pierDipi I'm working on it.
