### ISSUE TITLE
Investigate offset management

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#380]
We should investigate if we need offset management when using vertx kafka client and web client which are async.

## Additional Info

- https://github.com/strimzi/strimzi-kafka-bridge/blob/d782d3ff87edd7e47cdf2c87d480c26cbf8a87d5/src/main/java/io/strimzi/kafka/bridge/SinkBridgeEndpoint.java#L62-L63
- https://github.com/strimzi/strimzi-kafka-bridge/blob/b9fd6b7b462dfa7c08add87a3875a33f8887a522/src/main/java/io/strimzi/kafka/bridge/tracker/SimpleOffsetTracker.java
- https://github.com/strimzi/strimzi-kafka-bridge/blob/b9fd6b7b462dfa7c08add87a3875a33f8887a522/src/main/java/io/strimzi/kafka/bridge/tracker/FullOffsetTracker.java

- https://console.cloud.google.com/storage/browser/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka-broker/369/pull-knative-sandbox-eventing-kafka-broker-integration-tests/1323232785825009664/artifacts/98a01d98-1d02-11eb-9b07-ba5e5d672405/knative-eventing-logs/knative-eventing?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&forceOnObjectsSortingFiltering=false

- https://00f74ba44b1d15b084db7ed9df0f0e1f2dfe42897b-apidata.googleusercontent.com/download/storage/v1/b/knative-prow/o/pr-logs%2Fpull%2Fknative-sandbox_eventing-kafka-broker%2F369%2Fpull-knative-sandbox-eventing-kafka-broker-integration-tests%2F1323232785825009664%2Fartifacts%2F98a01d98-1d02-11eb-9b07-ba5e5d672405%2Fknative-eventing-logs%2Fknative-eventing%2Fkafka-broker-dispatcher-6d8d7964df-ssjwv-kafka-broker-dispatcher.log?jk=AFshE3WkEVySZQ7MGl3RPRyYcEwK_GPt7oXd_v3aQapaubt6kBAbKwaHB35YkMv-jEXVtGYfVlJQpzvXJ8JDlITgFsf1qAZVaASPlA_zdbafWOU1UONHSX3fZhBbOPrEE-_vBXFEeh--JNu35yjndtxNEZvkG1ois4N4KSbt_YjryesKdrL9esLk4_wEEAH217BTz5HMuNsl6rHWC9AXM-Y96qF5bp2my5amQGEI3zvblgyqVRPA38APjV91NAlb30V34fo6UFU_OPtCgwz1JcbuyTPMurayf1kdRadfrLdJbgFYlUaLzKVj5EdyXvl5NvV7gb81NH3kosNvFWhbEQN8cVDwDqDTjHNjxeqKd7PwcU_ndo5MTeSUZlEgHl8ggKoJKLy5BXdFVX0q3J2E3QkK1DkkEhfRJxRbyXAhHcyGEXWEPT4piEzzU3E1E-pBssOQxvPCKF3_dPhs6UgvWpCMytcmLN10n4kPCFooixBMgHiQD0d34wrDnRVKToA7yvFQNmRbYiW18F3O_il87lcBajPXVVR1F_O1crUv0fgXioyY5JxPMsQ4H9FrBJQCL3t6BlYBYqvGUw4H44XEp-V602w-t5SENYYQGTfDrNwPcXjhzdTX1qiB6MWvc352OhOeN0zfjF9Hrb1B3Tn_8EzaNjFAcC76UOzCAi7kVDEnobdLdGCydzulzbC3tzWaH_y0Q_iZezGHQq60tDInc8MSZELBJAA4_VDdkF8Pdvadm1Ggn1eNY2P65i5elHSHp8C4cE356T1QVb0piPnpneOjYny40vt92TRtupORTvOQRBStNZSR_Cy_rC9sWyTms_L9RmTU6ixk0JebLSCeJu260tpSpGM-pzVUuZATZFJ-0ZhZMxBMdJ_6SjbNBWBSsHbnv9mIzg2gmvUI8XYwqFdr8ao4PmQjGqhF0CUioK4QkQ3BCPOLxZ6FQWqcgd-N21QPO5XRDDYbfYUwmAgft-QvJ2s7S_L3cMt8GbkfFFEuCsOsCyWRr-AJXG7by05BNevQwIIgGYIOftSpKHTk7QOK9xM9iYcc2AmDKfVO3W0SWBO4Nj_uVWRu78AUgm63aWN4DTn8tHmaxwT0fNNCB9LUkAMZ5TxR5ZUFUFWB-LAP-3keh_EjSReMTVGCWwIJqe22QJfDUqIISjKQ_W_46nTklZgVtRIVsmgbDS5-zoIvym6jfPO9FThKhgYcU8rwebqTECH9zTpGhjDQo_He3QhRKcvvZ4WEmiLLfjHPFtmgPQz_RXxhX_D9f30OaZQ&isca=1

/assign @slinkydeveloper

**Comment by slinkydeveloper** [comment]
This is an evidence of the issue: 

```
{"@timestamp":"2020-11-02T12:30:42.126Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11922","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11922}
{"@timestamp":"2020-11-02T12:30:42.126Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11922","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11922}
{"@timestamp":"2020-11-02T12:30:42.127Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11921","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11921}
{"@timestamp":"2020-11-02T12:30:42.127Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11921","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11921}
{"@timestamp":"2020-11-02T12:30:42.129Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11920","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11920}
{"@timestamp":"2020-11-02T12:30:42.129Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11920","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11920}
{"@timestamp":"2020-11-02T12:30:42.130Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11919","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11919}
{"@timestamp":"2020-11-02T12:30:42.130Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11919","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11919}
{"@timestamp":"2020-11-02T12:30:42.131Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11918","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11918}
{"@timestamp":"2020-11-02T12:30:42.131Z","@version":"1","message":"committed topic=knative-broker-sacura-broker partition=5 offset=11918","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.strategy.UnorderedConsumerRecordOffsetStrategy","thread_name":"vert.x-eventloop-thread-1","level":"DEBUG","level_value":10000,"topic":"knative-broker-sacura-broker","partition":5,"offset":11918}
```

It could well be the logger. In any case, I'm going to investigate
