### ISSUE TITLE
Add tests for Configurations.java

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#381]
## Expected Behavior

Tests for data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java

## Actual Behavior

No tests for data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java

## Additional Info

/good-first-issue
/area data-plane
/area test

**Comment by shyamrox** [comment]
I'll take this one.

**Comment by pierDipi** [comment]
Hi @shyamrox,
you can comment `/assign` get the issue assigned to you and let other people in the community know you're working on this issue.
