### ISSUE TITLE
0.19 Release notes

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#398]
We need to update the 0.19.0 release notes.

/cc @n3wscott

**Comment by pierDipi** [comment]
start sha: `3f3413d2b12321d848bfec7eb0bdf9b931e94740`
end sha: `a755d9717279be380424ea81775ab5093328d286`

**Comment by pierDipi** [comment]
Release notes: https://hackmd.io/QKQuE_WUQ5evLZj0F-o_Hg?both

/assign @n3wscott

**Comment by n3wscott** [comment]
Looks great, thanks! --> updated https://github.com/knative-sandbox/eventing-kafka-broker/releases/tag/v0.19.0

/close
