### ISSUE TITLE
Use W3CTraceContextPropagator instead of HttpTraceContext

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#466]
We bumped open telemetry from 0.11 to 0.12.0 in https://github.com/knative-sandbox/eventing-kafka-broker/pull/458.

Release notes mention this:
> The HttpTraceContext class has been deprecated in favor of W3CTraceContextPropagator. HttpTraceContext will be removed in 0.13.0.

We should replace all usages of `HttpTraceContext` to use `W3CTraceContextPropagator` in: https://github.com/knative-sandbox/eventing-kafka-broker/blob/b92bcd9eb938e3daad0e8756387732e34240f411/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryTracer.java

## Additional Info

/good-first-issue
/area data-plane
/kind removal

**Comment by OmarMorales71** [comment]
@arghya88 @pierDipi Could I take this issue?

**Comment by pierDipi** [comment]
Hi @OmarMorales71!
@arghya88 has already opened a PR for this issue: https://github.com/knative-sandbox/eventing-kafka-broker/pull/471.

You can pick up other issues tagged with `good-first-issues` or `help-wanted` such as https://github.com/knative-sandbox/eventing-kafka-broker/issues/468 or https://github.com/knative-sandbox/eventing-kafka-broker/issues/351. 
If you are actively working on an issue, comment `/assign` and our bot will assign it to you.
If an issue has the `good-first-issue` tag but you feel it is not clear enough feel free to ask questions by leaving a comment.
