### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#54]
We need to include this project inside the knative release process: https://knative.slack.com/archives/CR2141CGY/p1595329443245300

**Comment by pierDipi** [comment]
We have `nightly`, `dot-release`, and `auto-release` set up in `test-infra` (see https://testgrid.knative.dev/eventing-kafka-broker#Summary).
All we need is a `./hack/release.sh` file properly configured.

Probably worth following this approach: https://github.com/knative/eventing/issues/3513
