### ISSUE TITLE
Tracing E2E test

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#585]
**Problem**

We don't have a tracing E2E test.

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
2

**Additional context (optional)**

- Eventing tracing tests

**Comment by slinkydeveloper** [comment]
The new test should use reconciler-test, the new test framework https://github.com/knative-sandbox/reconciler-test
