### ISSUE TITLE
Speed up integration tests pipeline

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#596]
We should speed up our integration tests pipeline since it takes ~1h to complete.

Some ideas could be:
- Parallel test images upload and data plane or control plane build (or both)
- Parallel Kafka cluster deploy and data plane or control plane build (or both)

## Expected Behavior

integration tests pipeline tasks << 1h

## Actual Behavior

integration tests pipeline takes ~1h

## Steps to Reproduce the Problem

1. Just run integration tests

## Additional Info

- Increasing parallelism had been tried in other repositories and there are no advantages.
- The main pipeline flow is in https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/test/e2e-common.sh
- Ideally, we don't introduce too many bash scripts or functions

/area test
/kind performance

**Comment by pierDipi** [comment]
We're at 45 min.

---

> Parallel test images upload and data plane or control plane build (or both)
> Parallel Kafka cluster deploy and data plane or control plane build (or both)

Those don't help that much and they add complexity. (verified in https://github.com/knative-sandbox/eventing-kafka-broker/pull/607)

**Comment by slinkydeveloper** [comment]
Can this be considered done? Any other ideas you wanna try? :)

**Comment by pierDipi** [comment]
I see serving is using a very high parallel number:
https://github.com/knative/serving/blob/0751aed142e00726647a2042fcc1f587a9a7827a/test/e2e-tests.sh#L136

let's try this.

**Comment by pierDipi** [comment]
Let's close this, we've got 15m improvements, which is good for now.
