### ISSUE TITLE
Figure out how to get rid of keyValue for logging

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#641]
**Describe the bug**
Today we have `keyValue` scattered in different log statements, which are tied to the logging implementation

 **Expected behavior**
We should not be tied to the logging implementation, hence we should remove every statement that couple our code to logstash logback json encoder.

**Comment by slinkydeveloper** [comment]
/assign

I'm proceeding as following:

* All the debug statements won't have structured fields anymore (since structured fields are useful only for production logging infra, we don't need structured fields for logging statements that won't be used in production, aka level <= debug)
* For the remaining statements, I'm going to use the MDC https://github.com/logstash/logstash-logback-encoder#mdc-fields

**Comment by pierDipi** [comment]
> All the debug statements won't have structured fields anymore (since structured fields are useful only for production logging infra, we don't need structured fields for logging statements that won't be used in production, aka level <= debug)

This is not true, they are useful in CI

**Comment by pierDipi** [comment]
Please, let's not do this, _structured logging is important_ even in debug mode.

**Comment by slinkydeveloper** [comment]
> This is not true, they are useful in CI too

Do we actually have an infrastructure to read the json logs and search around it? And is it that fundamental? Do you have a solution that allows us to move away from our tight coupling to logstash json encoder?

**Comment by pierDipi** [comment]
> tight coupling to logstash json encoder

Why this is a problem now?

**Comment by pierDipi** [comment]
We have zap assumption all over Knative.

**Comment by pierDipi** [comment]
The linked PR is clearly an example of weird logging code:
```java
    MDC.put("id", egress.getUid());
    MDC.put("consumerGroup", egress.getConsumerGroup());
    MDC.put("destination", egress.getDestination());
    logger.error(msg, cause);
    MDC.clear();
```

**Comment by slinkydeveloper** [comment]
> Why this is a problem now?

Because I can't swap the slf4j implementation behind the hood, making slf4j useless (as you saw in the benchmark PR, I had to remove all the log lines using `keyValue` to remove the logging implementation). I wanted at some point to remove the json logging for e2e tests (like we did for eventing, json logs are unreadable for humans), using a simple `ConsoleEncoder`, but we can't do that with this tight coupling.

> The linked PR is clearly an example of weird logging code:

It's super weird, but I can't see a better solution and it's still better than using slf4j with types specific to the logging impl. Do you have any better solution that doesn't tight couple us to a specific logger impl?

**Comment by pierDipi** [comment]
The logger doesn't have to be `static`, it can be injected like any other dependency.

**Comment by slinkydeveloper** [comment]
> The logger doesn't have to be static, it can be injected like any other dependency.

I don't see how this solves the problem, and even worse, it's not idiomatic for the usage of slf4j

**Comment by pierDipi** [comment]
From http://www.slf4j.org/manual.html
```java
        int newT = 15;
        int oldT = 16;

        // using classical API
        logger.debug("oldT={} newT={} Temperature changed.", newT, oldT);

        // using fluent API
        logger.atDebug().addKeyValue("oldT", oldT).addKeyValue("newT", newT).log("Temperature changed.");     
```

**Comment by pierDipi** [comment]
^ SLF4J API version 2.0.0

**Comment by slinkydeveloper** [comment]
@pierDipi it sounds perfect! Will this work out with logstash json encoder? Any refs?

**Comment by pierDipi** [comment]
I don't know :man_shrugging:

**Comment by slinkydeveloper** [comment]
SLF4J doesn't sound actively developed, nor logback...

```
2.0.0-alpha1/                                     2019-10-01 19:09         -  
```

* https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
* https://repo1.maven.org/maven2/ch/qos/logback/logback-core/

**Comment by slinkydeveloper** [comment]
Ok I might have another solution, without scrambling too much our code

**Comment by pierDipi** [comment]
Log4J might be another valid option: https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/message/MapMessage.html#with-java.lang.String-boolean-

**Comment by pierDipi** [comment]
Re ^, an article https://www.elastic.co/guide/en/ecs-logging/java/current/_structured_logging_with_log4j2.html
