### ISSUE TITLE
Use <dependencyManagement> in parent data-plane pom

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#7]
**Problem**
Now the parent data plane pom contains a lot of dependencies that should be specified in child poms.

These should be removed but the parent pom should have the `<dependencyManagement>` definition to import the Vert.x BOM (https://github.com/vert-x3/vertx-stack#bills-of-materials-maven-bom) and the other dependencies versions (slf4j, junit5, ...).
Then the child modules just need to import the dep without explicating the version (this will keep the version aligned across all modules)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Contributor

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Comment by ohbus** [comment]
I would like to get started with this

**Comment by pierDipi** [comment]
Hi @ohbus, thanks for your interest in the project. :smile: 

You need to generate protobuf code by running `./proto/hack/generate_proto`

/assign @ohbus

**Comment by ohbus** [comment]
@pierDipi thanks for helping out.

I need to setup the enviornment before starting to work on the project. I am a slow learner and would really appreciate if you could guide me through the setps from [DEVELOPMENT.md](https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/DEVELOPMENT.md)

**Comment by pierDipi** [comment]
@ohbus for this specific task, you need to install docker following instructions here: https://docs.docker.com/get-docker/, Maven, and Java (Maven and Java seem already installed on your machine looking at the image you posted).
The rest of the steps are for this specific task unnecessary, you don't need to spin up a Kubernetes cluster.

Once it's all set up, follow instructions here: https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/DEVELOPMENT.md#checkout-your-fork, here https://github.com/knative-sandbox/eventing-kafka-broker/blob/master/DEVELOPMENT.md#code-generation, and then you can start working on this issue.

While you're working on it, if you want to run tests to make sure to not break things run `mvn clean verify` from inside the `data-plane` directory.

**Comment by ohbus** [comment]
Okay I already have everything except for the Kubernetes cluster, so let me do what you have said and then I can share you my progress.

**Comment by slinkydeveloper** [comment]
@ohbus any updates on this?
