### ISSUE TITLE
Add DeliveryOrder status condition or annotation for Trigger

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#732]
**Problem**
In https://github.com/knative-sandbox/eventing-kafka-broker/pull/701 we introduced a new annotation to configure the delivery order and during the discussion there, we come up to the conclusion that would like to have a status condition to give users feedback on it since we don't have a way to signal that the annotation has been read correctly.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
- Event consumer

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

- Discussion in https://github.com/knative-sandbox/eventing-kafka-broker/pull/701

**Comment by slinkydeveloper** [comment]
Added to #589
