### ISSUE TITLE
Simplify the local development loop

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#740]
Today we have a huge amount of scripts, very dependent on bash, which makes a whole more complex the local development loop.

We need to clean them up and make sure we have a super easy and documented local development loop.

Some actions I want to investigate:

* [ ] Single command build and deploy to local kind the infra for testing. There is already the sourcing of a script and then the run of `test_setup`, but it's dependent on bash, and we can have a script that just does that, or even have maven to do that. Maybe we can have a pom that does that? I've also found a funny thing I want to try it out :smiling_imp: https://github.com/raydac/mvn-golang 
* [ ] Single command to generate release artifacts for local testing (similar to above)
* [ ] Single command run sacura (similar to above)
* [ ] Single command run profiling (similar to above)
* [ ] proto generation can be moved to maven, where we can config a pom to emit both golang and java code, in the respective positions we want them. Some interesting example https://github.com/raydac/mvn-golang/blob/master/mvn-golang-examples/mvn-golang-example-protobuf/pom.xml
* [ ] Building images and pushing them to local kind doesn't really work (for data plane)

Some of these are already there, we might just need to simpligy their usage and/or document these.

We also need to make sure we don't diverge from the scripts used in CI. Preferably, the local dev scripts should be the same used by CI

/assign

**Comment by slinkydeveloper** [comment]
Also related: https://github.com/knative/test-infra/issues/2726

**Comment by pierDipi** [comment]
Sounds good! 

PS: I can do this with a makefile :') 

> Single command build and deploy to local kind the infra for testing. There is already the sourcing of a script and then the run of test_setup, but it's dependent on bash, and we can have a script that just does that, or even have maven to do that. Maybe we can have a pom that does that? I've also found a funny thing I want to try it out

Let's not be too edgy (please)

> Single command to generate release artifacts for local testing (similar to above)

```source test/e2e-common.sh && knative_setup && test_setup```

Done :heavy_check_mark: 

>  Single command run profiling (similar to above)

```./data-plane/profiler/run.sh```

Done :heavy_check_mark: 

> Single command run sacura (similar to above)

```source test/e2e-common.sh && apply_sacura```

Done :heavy_check_mark: 

> Building images and pushing them to local kind doesn't really work (for data plane)

Yeah, the `WITH_KIND` flag doesn't push images to a local kind but to `KO_DOCKER_REPO` which I've never tried to set to KinD local registry.

> We also need to make sure we don't diverge from the scripts used in CI. Preferably, the local dev scripts should be the same used by CI

This is not a problem today, we use basically ```source test/e2e-common.sh && knative_setup && test_setup``` in every E2E CI job

**Comment by pierDipi** [comment]
Perhaps a bit of documentation refresh could help?

**Comment by pierDipi** [comment]
>  proto generation can be moved to maven, where we can config a pom to emit both golang and java code, in the respective positions we want them. Some interesting example https://github.com/raydac/mvn-golang/blob/master/mvn-golang-examples/mvn-golang-example-protobuf/pom.xml

I'd like to use a proto version that fits our needs and is up to date regarding security and features, so having zero dependencies is better to achieve this, and don't see a benefit of putting 20+ lines of xml vs 17 lines of simple bash:

https://github.com/knative-sandbox/eventing-kafka-broker/blob/1258e973843974a5a7fc42aff651cab4ed2a3f56/proto/hack/generate_proto#L1-L17

**Comment by slinkydeveloper** [comment]
One word about sourcing scripts: it's amazing and it's a wonderful world, as soon as you remain in bash 4 :smile: Maybe an interactive easy script that includes all commands, without forcing me to source, might help?

In my ideal world, we should have a single entrypoint to do all the local dev operations... Let me think through it, I might prototype something for it.

> Perhaps a bit of documentation refresh could help?

Definitely, as I said at the beginning of the issue, maybe we already have all the above listed things but doc is not updated.

> Building images and pushing them to local kind doesn't really work (for data plane)

Yeah maybe it's just me that I did something wrong today while playing with it :smile:

**Comment by pierDipi** [comment]
> One word about sourcing scripts: it's amazing and it's a wonderful world, as soon as you remain in bash 4 smile Mac comes with zsh built-in and a lot of people like me uses zsh for the goodies it includes, compared to bash.

Interesting!

> Maybe an interactive easy script that includes all commands, without forcing me to source, might help? In my ideal world, we should have a single entrypoint to do all the local dev operations... Let me think through it, I might prototype something for it.

Makefile? :)

Anyway, let's refresh docs!

/assign

**Comment by slinkydeveloper** [comment]
> Makefile? :)

No please it's even a worse nightmare...

**Comment by slinkydeveloper** [comment]
Ok no wait, maybe makefiles easy as the one you proposed might do it

**Comment by slinkydeveloper** [comment]
Now that https://github.com/knative/test-infra/issues/2726 is merged, we can remove some of our containers to simplify the build @pierDipi. I'll give it a try!

**Comment by slinkydeveloper** [comment]
FYI @pierDipi https://github.com/knative-sandbox/eventing-kafka-broker/pull/657/files#diff-ceb05c276a33023b12e286f893fd967c03709f797d287ce8c208fe6af1ecc6abR38-R41 We should remove these 2 envs `SKIP_PUSH` and `WITH_KIND` and just recognize whether `KO_DOCKER_REPO` is equal to `kind.local`

**Comment by pierDipi** [comment]
+1,  I think we don't even need to recognize kind.local

**Comment by pierDipi** [comment]
It should just work

**Comment by slinkydeveloper** [comment]
@pierDipi it doesn't because docker don't know how to push to kind.local :(

**Comment by pierDipi** [comment]
Ok, then nvm

**Comment by pierDipi** [comment]
I can do it

**Comment by slinkydeveloper** [comment]
I think #749 fix this one. Reopen if you need it
