### ISSUE TITLE
Cloudevent Partitionkey not respected

### ISSUE THREAD

**Issue by dahateb** [knative-sandbox/eventing-kafka-broker#761]
**Describe the bug**
Sending the Partitionkey header is not respected in the Kafka topic. 
PR https://github.com/knative-sandbox/eventing-kafka-broker/pull/751 should have fixed this, but I still cannot see the partitionkey set on the kafka topic

 **Expected behavior**
Messages where the cloud header `Ce-Partitionkey` is set end up in the same Partition. Partitionkey is set in the topic

 **To Reproduce**
1. Create Kafka Broker, Trigger and Sink Service. Namespace is `kt-kfk-broker`
2. run the command multiple times:
```
curl -v "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/kt-kfk-broker/default"  -X POST  -H "Ce-Id: say-hello"  -H "Ce-Specversion: 1.0"  -H "Ce-Type: aloha"  -H "Ce-Source: mycurl" -H "Ce-partionkey: test1234"  -H "Content-Type: application/json"  -d '{"key":"test test test 0004"}'
```
3. run consumer on broker topic
```
kubectl run kafka-consumer -ti --image=quay.io/strimzi/kafka:0.21.0-kafka-2.7.0 --rm=true --restart=Never -- bin/kafka-console-consumer.sh --bootstrap-server elk-platform-kafka-cluster-kafka-bootstrap.data-platform.svc.cluster.local:9092 --topic knative-broker-kt-kfk-broker-default --from-beginning --property print.key=true --property print.headers=true --property print.partition=true
```
4. Messages end up in different topics and partitionkey is null
```
Partition:3	ce_specversion:1.0,ce_id:say-hello,ce_source:mycurl,ce_type:aloha,content-type:application/json,ce_partionkey:test1234	null	{"key":"test test test 0004"}
Partition:8	ce_specversion:1.0,ce_id:say-hello,ce_source:mycurl,ce_type:aloha,content-type:application/json,ce_partionkey:test1234	null	{"key":"test test test 0004"}
```

 **Knative release version**
v0.21.2

 **Additional context**
used strimzi Kafka version is 0.21.0 with Kafka 2.6

**Comment by slinkydeveloper** [comment]
Maybe the problem is the mispelling of `Ce-partionkey`? It should be `Ce-partitionkey`

BTW, I've added a test for it too https://github.com/knative-sandbox/eventing-kafka-broker/pull/756

**Comment by dahateb** [comment]
My bad, the misspelling is indeed the issue. Sorry to bother there
