### ISSUE TITLE
Change 'auth.secret.ref.name' in KafkaSing to camel case

### ISSUE THREAD

**Issue by rhuss** [knative-sandbox/eventing-kafka-broker#787]
According to https://knative.dev/docs/eventing/sink/kafka-sink/, the field for referencing an authentication `Secret` is called `auth.secret.ref.name`. Is there any particular reason why this name does not follow the usual camelCase convention for naming (like `bootstrapServers`) and could this be changed please to e.g. `secretReference` or `secretRef` or `authSecret` etc. ?

**Comment by pierDipi** [comment]
Docs is wrong the structure is:

```yaml
auth:
  secret:
    ref:
      name: <secret_name>
```

**Comment by pierDipi** [comment]
Do you think your renaming proposal still applies?

**Comment by pierDipi** [comment]
https://github.com/knative/docs/pull/3438

**Comment by slinkydeveloper** [comment]
This seems to be fixed with the docs PR, reopen if you need it
