### ISSUE TITLE
Set up Jacoco to produce an aggregate code coverage report

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#8]
**Problem**
Jacoco code coverage report produces multiple reports, one per module (core, receiver, etc)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Contributor

**Exit Criteria**
Jacoco produces an aggregated code coverage report of all modules and the report is integrated with the coverage infrastructure.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Comment by slinkydeveloper** [comment]
https://github.com/knative-sandbox/eventing-kafka-broker/pull/159 partially fixes this issue: now the report is correctly generated in `/data-plane/target/jacoco`, but it's not persisted in the CI `$ARTIFACT` dir

**Comment by pierDipi** [comment]
We don't need the CI integration anymore since we're using codecov: https://github.com/knative-sandbox/eventing-kafka-broker/pull/195
/close
