### ISSUE TITLE
Third party file should be checked by the codegen

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#844]
**Problem**
We have a third party file codegenerated by maven which is not checked by our codegen, generating merge conflicts

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Knative developer

**Exit Criteria**
Third party file should be checked by the codegenerator check

**Time Estimate (optional):** 
1

**Comment by pierDipi** [comment]
Unfortunately, this would prevent us from using dependabot.

**Comment by slinkydeveloper** [comment]
> Unfortunately, this would prevent us from using dependabot.

Why?

**Comment by pierDipi** [comment]
Auditing dependencies' licenses.

**Comment by pierDipi** [comment]
Dependabot can't run maven plugins after updating the pom file.

**Comment by slinkydeveloper** [comment]
> Auditing dependencies' licenses.

Is that so important? Is there some requirement for that?

**Comment by pierDipi** [comment]
No, afaik

**Comment by slinkydeveloper** [comment]
I'm gonna ask it to thu TOC about that.

**Comment by slinkydeveloper** [comment]
https://groups.google.com/u/0/g/knative-dev/c/VsD5BUAIRwg

**Comment by pierDipi** [comment]
Thank you!

**Comment by slinkydeveloper** [comment]
So we need to keep this file, and we can't automate it without changing dependabot :(

**Comment by slinkydeveloper** [comment]
FYI https://github.com/dependabot/dependabot-core/issues/3622
