### ISSUE TITLE
[Experimental feature] Control protocol

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#853]
**Description**
Today we use a shared ConfigMap as the approach to let control plane communicate the contract to the data plane. This approach has several short-comings, most notably #337.

Recently a new approach to share the contract was developed, using the new https://github.com/knative-sandbox/control-protocol. Control protocol, among various benefits, creates a bi-directional "communication channel" between control plane and data plane, allowing the data plane to notify back readyness and solve other issues we face today. 

This experimental feature proposes an approach to replace the ConfigMap approach gradually with control protocol. It's out of the scope of this proposal to change the secrets retrieval logic and the status update logic, although these will benefit from the work that will be done here.

**Exit Criteria**
No ConfigMap is used anymore to share the data plane contract, instead the control-protocol is used.

**Experimental feature stages plan**
Below the proposed plan for the feature stages (this list implicitly includes the requirements defined in the process)

* Before implementing the feature, we need some preliminary work to implement the control protocol in Java:
  * [ ] Implement TCP protocol https://github.com/knative-sandbox/eventing-kafka-broker/pull/657
  * [ ] Create an interface like the Golang `control.Service` to simplify the usage and abstract from the tcp protocol itself.
  * [ ] Check and implement missing bits for TLS certificate rotation
  * [ ] Analyze if there's any need for a retry behaviour and how it should work
* Alpha:
  * [ ] Implement an alternative reconciliation code (both for sink and for broker) to use control protocol, instead of the CM.
  * [ ] Flag documentation
* Beta graduation as soon as 1 release after the inception
* Beta:
  * [ ] Implementation improvements
  * [ ] Encrypt with mTLS the control connection
* Stable graduation as soon as 2 release after the beta graduation
* Stable:
  * [ ] Remove the CM reconciliation code and the CM completely

**Affected WG**

* Event delivery WG

**Prior/related discussions**

* #337
* #785

**Comment by pierDipi** [comment]
Note without #785 working on #337 is not useful, since scheduling 1k consumers on a single pod doesn't make sense anyway.

**Comment by slinkydeveloper** [comment]
@pierDipi Yeah I know, the goal of this features is not to fix directly #337, I know #785 is the solution for it. This feature is about providing the means for fixing the CM limit, have proper status report, support at some point pause/restart and so on.
