### ISSUE TITLE
Split Resource Ingress and Resource Egress in separate resources

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#973]
**Problem**
Today our contract is organized as follows:

![plantuml(3)](https://user-images.githubusercontent.com/6706544/121368375-51596a80-c93b-11eb-86d5-b87d925a2235.png)

This contract modelling has certain shortcomings, most notably it doesn't map to the way the implementation is organized: receiver cares only about ingress contracts, dispatcher cares only about egress contracts.

I propose to reorganize the contract as follows:

![plantuml(4)](https://user-images.githubusercontent.com/6706544/121368785-9ed5d780-c93b-11eb-9bc8-329a2dedbf09.png)

In other words, I propose to split completely Ingress and Egress and get rid of the Resource entity, duplicating eventual fields required in both Ingress and Egress.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Developer

**Exit Criteria**

Contract is organized as explained above

**Additional context (optional)**

This is going to simplify the implementation of #312 and #313. This will also allow us to have potentially different config maps, one for the "ingress contracts" and one for the "egress contracts", mitigating #337. Splitting in different CMs can be tackled in another issue.

**Comment by slinkydeveloper** [comment]
cc @pierDipi I know this is something we discussed about a while ago, wdyt about it?

**Comment by pierDipi** [comment]
We chatted about this a while ago. 

What I think is that we should optimize to save space more than everything else.
The current contract is optimized for saving space.

Why do you think that this will simplify #312 and #313? 
We should already have everything in place to implement them pretty easily.

> This contract modeling has certain shortcomings, most notably it doesn't map to the way the implementation is organized: receiver cares only about ingress contracts, dispatcher cares only about egress contracts.

We can do that even with the current contract too and mitigate #337, as follow:

- broker reconciler can use a CM (A) and fill only resource and ingress, 
- the trigger reconciler can use another CM (B) and fill only resource and egress.

**Comment by pierDipi** [comment]
I think I don't understand your reasons fully.

**Comment by slinkydeveloper** [comment]
> We can do that even with the current contract too and mitigate #337, as follow:
>    broker reconciler can use a CM (A) and fill only resource and ingress,
>    the trigger reconciler can use another CM (B) and fill only resource and egress.


That's what I want to do, but TBH I don't like the idea of reusing the same Resource type. What about:

* Because Resource <-> Ingress is a 1:1 association, Ingress just get the fields it needs from Resource
* Resource <-> Egress is 1:many association, so we could have something like Egresses (name to be bikeshed) where the Resource fields goes

My more "long term" vision about the contract is to have a way we will be able to send to the data plane (no matter what's the communication mean) single ingress and egresses. That's something we don't need to do now, until we know what this communication mean is, but maybe this issue is a good step forward in that direction.

**Comment by pierDipi** [comment]
Ok, let's then build a plan on how to upgrade safely after this change.

**Comment by slinkydeveloper** [comment]
@pierDipi Agreed, I think we should have some fancy upgrader job that clean up the bad CMs and creates the new one, then touches all the broker and trigger resources so these get reconciled.

Actually, if in the context of this issue we also split in 2 config maps, we won't even need to remove the old CM, we can just ask the user to do so, we only need to touch all the resources to re-reconcile them.

I'm also thinking that we should get the upgrade tests in at some point before moving forward with this one...

**Comment by pierDipi** [comment]
> Actually, if in the context of this issue we also split in 2 config maps, we won't even need to remove the old CM, we can just ask the user to do so, we only need to touch all the resources to re-reconcile them.

No need to touch all resources, once a controller starts it queues and reconciles all resources.
